/* Generated by Nim Compiler v0.18.1 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <sys/types.h>
                          #include <pthread.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A;
typedef struct tyObject_ExtraData_aRbi7557vgG4KV47nk1CWQ tyObject_ExtraData_aRbi7557vgG4KV47nk1CWQ;
typedef struct tyObject_Table_zjMaDBasw1LnKbj11akpfw tyObject_Table_zjMaDBasw1LnKbj11akpfw;
typedef struct tySequence_pUxI6Ljo6IKKHXKOZkQ7Og tySequence_pUxI6Ljo6IKKHXKOZkQ7Og;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyTuple_p49cp3DD9aai5K1o5mfF67vw tyTuple_p49cp3DD9aai5K1o5mfF67vw;
typedef struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA;
typedef struct tyTuple_sr3s7uVHpu9cEbbDnCSg8yQ tyTuple_sr3s7uVHpu9cEbbDnCSg8yQ;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw;
typedef struct tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw;
typedef struct tyObject_SyntaxErrorcolonObjectType__JKyk7RuO2Y7QBAE9aLjFv9bA tyObject_SyntaxErrorcolonObjectType__JKyk7RuO2Y7QBAE9aLjFv9bA;
typedef struct tyObject_RegexErrorcolonObjectType__GpPe019cJO4uVSU1kDvvJdQ tyObject_RegexErrorcolonObjectType__GpPe019cJO4uVSU1kDvvJdQ;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_StudyErrorcolonObjectType__iukRLg9aUkCVGWqRsfNRcow tyObject_StudyErrorcolonObjectType__iukRLg9aUkCVGWqRsfNRcow;
typedef struct tyObject_FieldError_cFRnc8M9cG1X9b9cx0eykcZfA tyObject_FieldError_cFRnc8M9cG1X9b9cx0eykcZfA;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_Table_zjMaDBasw1LnKbj11akpfw {
tySequence_pUxI6Ljo6IKKHXKOZkQ7Og* data;
NI counter;
};
struct tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw {
NimStringDesc* pattern;
tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A* pcreObj;
tyObject_ExtraData_aRbi7557vgG4KV47nk1CWQ* pcreExtra;
tyObject_Table_zjMaDBasw1LnKbj11akpfw captureNameToId;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyTuple_p49cp3DD9aai5K1o5mfF67vw {
NimStringDesc* Field0;
NI Field1;
NIM_BOOL Field2;
};
struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA {
NI a;
NI b;
};
typedef NimStringDesc* tyArray_rmMMhDIqORJzUU5zqeitSQ[16];
struct tyTuple_sr3s7uVHpu9cEbbDnCSg8yQ {
NI Field0;
NimStringDesc* Field1;
NI Field2;
};
typedef N_CDECL_PTR(void, tyProc_5cp59bim9aJ4WupX5aVaD1Sg) (NCSTRING stringptr);
typedef N_CDECL_PTR(void, tyProc_hMR3nXvmHGbyZzcDul78bg) (tyObject_ExtraData_aRbi7557vgG4KV47nk1CWQ* extra);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
typedef long tyArray_xDUyu9aScDpt0JZLU6q9aEZQ[5];
struct tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw {
tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* head;
tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* tail;
pthread_mutex_t lock;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw toDispose;
NI gcThreadId;
};
typedef N_CDECL_PTR(tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A*, tyProc_OMNNRjh8IIE9bAc9btZcg0NA) (NCSTRING pattern, int options, NCSTRING* errptr, int* erroffset, void* tableptr);
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_RegexErrorcolonObjectType__GpPe019cJO4uVSU1kDvvJdQ {
  Exception Sup;
};
struct tyObject_SyntaxErrorcolonObjectType__JKyk7RuO2Y7QBAE9aLjFv9bA {
  tyObject_RegexErrorcolonObjectType__GpPe019cJO4uVSU1kDvvJdQ Sup;
NI pos;
NimStringDesc* pattern;
};
typedef N_CDECL_PTR(int, tyProc_KqPl2ltkjnSoyb04zAVCAQ) (int what, void* where);
typedef N_CDECL_PTR(tyObject_ExtraData_aRbi7557vgG4KV47nk1CWQ*, tyProc_qU2uMIyWirSwn1Nd4hJjDw) (tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A* code, int options, NCSTRING* errptr);
struct tyObject_StudyErrorcolonObjectType__iukRLg9aUkCVGWqRsfNRcow {
  tyObject_RegexErrorcolonObjectType__GpPe019cJO4uVSU1kDvvJdQ Sup;
};
typedef N_CDECL_PTR(int, tyProc_urwqljFnOeCDcw8gOFcrpg) (tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A* code, tyObject_ExtraData_aRbi7557vgG4KV47nk1CWQ* extra, int what, void* where);
struct tyObject_FieldError_cFRnc8M9cG1X9b9cx0eykcZfA {
  Exception Sup;
};
typedef NimStringDesc* tyArray_Re75IspeoxXy2oCZHwcRrA[2];
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence_pUxI6Ljo6IKKHXKOZkQ7Og {
  TGenericSeq Sup;
  tyTuple_sr3s7uVHpu9cEbbDnCSg8yQ data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_b2AcSq8fDE9aZulLX3In9a7g)(void* p, NI op);
static N_NIMCALL(void, TM_KiNTuQ9alifhptBrRwE19b2A_3)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_LIB_PRIVATE N_NIMCALL(tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw*, re_5YObgtpedTBKZLpqEDsMpg)(NimStringDesc* pattern);
N_LIB_PRIVATE N_NIMCALL(void, extractOptions_9aLyPIoKa7QTA03XJxQTIeA)(NimStringDesc* pattern, tyTuple_p49cp3DD9aai5K1o5mfF67vw* Result);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(NimStringDesc*, X5BX5D__xiaaX9b4cczHG39bivOynT9bgnre)(NimStringDesc* s, tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5Qnre)(NI a, NI b);
static N_INLINE(NIM_BOOL, contains_jPdUhZfr9a8sH2V3ZBDljzwnre)(NimStringDesc** a, NI aLen_0, NimStringDesc* item);
static N_INLINE(NI, find_9basNl9bVqn7SOf9bgUeI8TEQnre)(NimStringDesc** a, NI aLen_0, NimStringDesc* item);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQnre)(void* a, void* b, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey_DyKLR1cNLT9cYc2bz5XA9cYw)(tyObject_Table_zjMaDBasw1LnKbj11akpfw t, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(NI, X5BX5D__3uHbWNTgkIuCFgSUKhN19bg)(tyObject_Table_zjMaDBasw1LnKbj11akpfw t, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw*, initRegex_9b7dPCPhepIsjVMqyciPoDg)(NimStringDesc* pattern, NI flags, NIM_BOOL study);
N_LIB_PRIVATE N_NIMCALL(void, destroyRegex_XgDJaQTWYPopj0N33Dv15g)(tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw* pattern);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_NIMCALL(void, Marker_tyRef_4Y8poQHbErL2uzGraWOOmw)(void* p, NI op);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
static N_INLINE(NIM_BOOL, eqeq__9ccNWqrTIE9bcAqE2Q0ro7zgnre)(NCSTRING x, NCSTRING y);
static N_NIMCALL(void, Marker_tyRef_ouvOCYwP8k3PEYE9bP5THng)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(void, getNameToNumberTable_ia87UBnQeDAD9bB1fS1AL9cQ)(tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw* pattern, tyObject_Table_zjMaDBasw1LnKbj11akpfw* Result);
N_LIB_PRIVATE N_NIMCALL(int, getinfo_I69cDrsTKnD5deWeuo8Hivg)(tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw* pattern, int opt);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen_0);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(NI, getinfo_m2U5mq0ZzHKP9bxvWmMXf5w)(tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw* pattern, int opt);
N_LIB_PRIVATE N_NIMCALL(void, initTable_3Cf7Fyn7tUxJRodC9aUxtFw)(NI initialSize, tyObject_Table_zjMaDBasw1LnKbj11akpfw* Result);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__ElMq9artIyfSkc1PsoGBTww)(tyObject_Table_zjMaDBasw1LnKbj11akpfw* t, NimStringDesc* key, NI val);
tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw* SpecialCharMatcher_79aI60tu0f8LeTOA0JymnBQ;
TNimType NTI_ULxINHgL1NYel7wmacOU9aw_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI_WH9aVfHDhtZbU6Y5QgauqZQ_;
extern TNimType NTI_z1uZWlkSdiDfd9ahW9a6Ibug_;
extern TNimType NTI_zjMaDBasw1LnKbj11akpfw_;
TNimType NTI_b2AcSq8fDE9aZulLX3In9a7g_;
TNimType NTI_p49cp3DD9aai5K1o5mfF67vw_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
extern tyProc_5cp59bim9aJ4WupX5aVaD1Sg Dl_275691_;
extern tyProc_hMR3nXvmHGbyZzcDul78bg Dl_275758_;
extern NIM_THREADVAR tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern tyProc_OMNNRjh8IIE9bAc9btZcg0NA Dl_275601_;
extern TNimType NTI_bAvOj2UcojKN87yAQLs0aw_;
TNimType NTI_GpPe019cJO4uVSU1kDvvJdQ_;
TNimType NTI_JKyk7RuO2Y7QBAE9aLjFv9bA_;
TNimType NTI_4Y8poQHbErL2uzGraWOOmw_;
extern tyProc_KqPl2ltkjnSoyb04zAVCAQ Dl_275623_;
extern tyProc_qU2uMIyWirSwn1Nd4hJjDw Dl_275750_;
TNimType NTI_iukRLg9aUkCVGWqRsfNRcow_;
TNimType NTI_ouvOCYwP8k3PEYE9bP5THng_;
extern tyProc_urwqljFnOeCDcw8gOFcrpg Dl_275697_;
extern TNimType NTI_UhsUhdse8ntQEMKWaJuOMw_;
extern TNimType NTI_cFRnc8M9cG1X9b9cx0eykcZfA_;
STRING_LITERAL(TM_KiNTuQ9alifhptBrRwE19b2A_6, "", 0);
NIM_CONST tyTuple_p49cp3DD9aai5K1o5mfF67vw TM_KiNTuQ9alifhptBrRwE19b2A_5 = {((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_6),
((NI) 0),
NIM_TRUE}
;
STRING_LITERAL(TM_KiNTuQ9alifhptBrRwE19b2A_8, "LIMIT_MATCH=", 12);
STRING_LITERAL(TM_KiNTuQ9alifhptBrRwE19b2A_9, "LIMIT_RECURSION=", 16);
STRING_LITERAL(TM_KiNTuQ9alifhptBrRwE19b2A_10, "NO_AUTO_POSSESS", 15);
STRING_LITERAL(TM_KiNTuQ9alifhptBrRwE19b2A_11, "NO_START_OPT", 12);
STRING_LITERAL(TM_KiNTuQ9alifhptBrRwE19b2A_12, "UTF8", 4);
STRING_LITERAL(TM_KiNTuQ9alifhptBrRwE19b2A_13, "UTF16", 5);
STRING_LITERAL(TM_KiNTuQ9alifhptBrRwE19b2A_14, "UTF32", 5);
STRING_LITERAL(TM_KiNTuQ9alifhptBrRwE19b2A_15, "UTF", 3);
STRING_LITERAL(TM_KiNTuQ9alifhptBrRwE19b2A_16, "UCP", 3);
STRING_LITERAL(TM_KiNTuQ9alifhptBrRwE19b2A_17, "CR", 2);
STRING_LITERAL(TM_KiNTuQ9alifhptBrRwE19b2A_18, "LF", 2);
STRING_LITERAL(TM_KiNTuQ9alifhptBrRwE19b2A_19, "CRLF", 4);
STRING_LITERAL(TM_KiNTuQ9alifhptBrRwE19b2A_20, "ANYCRLF", 7);
STRING_LITERAL(TM_KiNTuQ9alifhptBrRwE19b2A_21, "ANY", 3);
STRING_LITERAL(TM_KiNTuQ9alifhptBrRwE19b2A_22, "BSR_ANYCRLF", 11);
STRING_LITERAL(TM_KiNTuQ9alifhptBrRwE19b2A_23, "BSR_UNICODE", 11);
NIM_CONST tyArray_rmMMhDIqORJzUU5zqeitSQ TM_KiNTuQ9alifhptBrRwE19b2A_7 = {((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_8),
((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_9),
((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_10),
((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_11),
((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_12),
((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_13),
((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_14),
((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_15),
((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_16),
((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_17),
((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_18),
((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_19),
((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_20),
((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_21),
((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_22),
((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_23)}
;
STRING_LITERAL(TM_KiNTuQ9alifhptBrRwE19b2A_25, "", 0);
STRING_LITERAL(TM_KiNTuQ9alifhptBrRwE19b2A_26, "DOLLAR_ENDONLY", 14);
STRING_LITERAL(TM_KiNTuQ9alifhptBrRwE19b2A_27, "JAVASCRIPT_COMPAT", 17);
STRING_LITERAL(TM_KiNTuQ9alifhptBrRwE19b2A_28, "NO_AUTO_CAPTURE", 15);
STRING_LITERAL(TM_KiNTuQ9alifhptBrRwE19b2A_29, "ANCHORED", 8);
STRING_LITERAL(TM_KiNTuQ9alifhptBrRwE19b2A_30, "FIRSTLINE", 9);
STRING_LITERAL(TM_KiNTuQ9alifhptBrRwE19b2A_31, "NEVER_UTF", 9);
STRING_LITERAL(TM_KiNTuQ9alifhptBrRwE19b2A_32, "U", 1);
NIM_CONST struct {
  TGenericSeq Sup;
  tyTuple_sr3s7uVHpu9cEbbDnCSg8yQ data[16];
} TM_KiNTuQ9alifhptBrRwE19b2A_33 = {{16, 16}, {{((NI) 0),
((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_25),
((NI) 0)}
,
{((NI) 0),
((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_25),
((NI) 0)}
,
{((NI) 0),
((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_25),
((NI) 0)}
,
{((NI) 0),
((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_25),
((NI) 0)}
,
{((NI) IL64(2416578405726479780)),
((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_26),
((NI) 32)}
,
{((NI) IL64(7042608792243335300)),
((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_27),
((NI) 33554432)}
,
{((NI) 0),
((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_25),
((NI) 0)}
,
{((NI) 0),
((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_25),
((NI) 0)}
,
{((NI) 0),
((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_25),
((NI) 0)}
,
{((NI) 0),
((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_25),
((NI) 0)}
,
{((NI) 0),
((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_25),
((NI) 0)}
,
{((NI) IL64(-3082112966781669)),
((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_28),
((NI) 4096)}
,
{((NI) IL64(3611635209622039676)),
((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_29),
((NI) 16)}
,
{((NI) IL64(1430235610613259308)),
((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_30),
((NI) 262144)}
,
{((NI) IL64(7104590895640073134)),
((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_31),
((NI) 65536)}
,
{((NI) IL64(25438148703)),
((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_32),
((NI) 536872960)}
}};
NIM_CONST tyObject_Table_zjMaDBasw1LnKbj11akpfw TM_KiNTuQ9alifhptBrRwE19b2A_24 = {((tySequence_pUxI6Ljo6IKKHXKOZkQ7Og*)&TM_KiNTuQ9alifhptBrRwE19b2A_33), ((NI) 7)};
STRING_LITERAL(TM_KiNTuQ9alifhptBrRwE19b2A_34, "NO_STUDY", 8);
STRING_LITERAL(TM_KiNTuQ9alifhptBrRwE19b2A_36, "Invalid getinfo for $1, errno $2", 32);
STRING_LITERAL(TM_KiNTuQ9alifhptBrRwE19b2A_37, "([\\\\+*\?[^\\]$(){}=!<>|:-])", 25);
static N_NIMCALL(void, Marker_tyRef_b2AcSq8fDE9aZulLX3In9a7g)(void* p, NI op) {
	tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw* a;
	a = (tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw*)p;
	nimGCvisit((void*)(*a).pattern, op);
	nimGCvisit((void*)(*a).captureNameToId.data, op);
}
static N_NIMCALL(void, TM_KiNTuQ9alifhptBrRwE19b2A_3)(void) {
	nimGCvisit((void*)SpecialCharMatcher_79aI60tu0f8LeTOA0JymnBQ, 0);
}

static N_INLINE(NimStringDesc*, X5BX5D__xiaaX9b4cczHG39bivOynT9bgnre)(NimStringDesc* s, tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x) {
	NimStringDesc* result;
	NI a;
	NI L;
	result = (NimStringDesc*)0;
	a = x.a;
	L = (NI)((NI)(x.b - a) + ((NI) 1));
	result = mnewString(((NI) (L)));
	{
		NI i;
		NI i_2;
		i = (NI)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				if (!(i_2 < L)) goto LA3;
				i = i_2;
				result->data[i] = s->data[(NI)(i + a)];
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	return result;
}

static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5Qnre)(NI a, NI b) {
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA result;
	memset((void*)(&result), 0, sizeof(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA));
	result.a = a;
	result.b = b;
	return result;
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQnre)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQnre(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, find_9basNl9bVqn7SOf9bgUeI8TEQnre)(NimStringDesc** a, NI aLen_0, NimStringDesc* item) {
	NI result;
{	result = (NI)0;
	{
		NimStringDesc* i;
		NI i_2;
		i = (NimStringDesc*)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				if (!(i_2 < aLen_0)) goto LA3;
				i = a[i_2];
				{
					if (!eqStrings(i, item)) goto LA6_;
					goto BeforeRet_;
				}
				LA6_: ;
				result += ((NI) 1);
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	result = ((NI) -1);
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NIM_BOOL, contains_jPdUhZfr9a8sH2V3ZBDljzwnre)(NimStringDesc** a, NI aLen_0, NimStringDesc* item) {
	NIM_BOOL result;
	NI T1_;
{	result = (NIM_BOOL)0;
	T1_ = (NI)0;
	T1_ = find_9basNl9bVqn7SOf9bgUeI8TEQnre(a, aLen_0, item);
	result = (((NI) 0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_LIB_PRIVATE N_NIMCALL(void, extractOptions_9aLyPIoKa7QTA03XJxQTIeA)(NimStringDesc* pattern, tyTuple_p49cp3DD9aai5K1o5mfF67vw* Result) {
	NI optionStart;
	NIM_BOOL equals;
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T57_;
	NimStringDesc* T58_;
	genericReset((void*)Result, (&NTI_p49cp3DD9aai5K1o5mfF67vw_));
	unsureAsgnRef((void**) (&(*Result).Field0), copyString(TM_KiNTuQ9alifhptBrRwE19b2A_5.Field0));
	(*Result).Field1 = TM_KiNTuQ9alifhptBrRwE19b2A_5.Field1;
	(*Result).Field2 = TM_KiNTuQ9alifhptBrRwE19b2A_5.Field2;
	optionStart = ((NI) 0);
	equals = NIM_FALSE;
	{
		NI i;
		NIM_CHAR c;
		NI i_2;
		i = (NI)0;
		c = (NIM_CHAR)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				if (!(i_2 < (pattern ? pattern->Sup.len : 0))) goto LA3;
				i = i_2;
				c = pattern->data[i_2];
				{
					if (!(optionStart == i)) goto LA6_;
					{
						if (!!(((NU8)(c) == (NU8)(40)))) goto LA10_;
						goto LA1;
					}
					LA10_: ;
					optionStart = i;
				}
				goto LA4_;
				LA6_: ;
				{
					if (!(optionStart == (NI)(i - ((NI) 1)))) goto LA13_;
					{
						if (!!(((NU8)(c) == (NU8)(42)))) goto LA17_;
						goto LA1;
					}
					LA17_: ;
				}
				goto LA4_;
				LA13_: ;
				{
					NimStringDesc* name;
					tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T22_;
					if (!((NU8)(c) == (NU8)(41))) goto LA20_;
					T22_ = dotdot__vDQySKWzgnxQdUarow6k5Qnre((NI)(optionStart + ((NI) 2)), (NI)(i - ((NI) 1)));
					name = X5BX5D__xiaaX9b4cczHG39bivOynT9bgnre(pattern, T22_);
					{
						NIM_BOOL T25_;
						tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T29_;
						NimStringDesc* T30_;
						T25_ = (NIM_BOOL)0;
						T25_ = equals;
						if (T25_) goto LA26_;
						T25_ = contains_jPdUhZfr9a8sH2V3ZBDljzwnre(TM_KiNTuQ9alifhptBrRwE19b2A_7, 16, name);
						LA26_: ;
						if (!T25_) goto LA27_;
						T29_ = dotdot__vDQySKWzgnxQdUarow6k5Qnre(optionStart, i);
						T30_ = (NimStringDesc*)0;
						T30_ = X5BX5D__xiaaX9b4cczHG39bivOynT9bgnre(pattern, T29_);
						(*Result).Field0 = resizeString((*Result).Field0, T30_->Sup.len + 0);
appendString((*Result).Field0, T30_);
					}
					goto LA23_;
					LA27_: ;
					{
						NIM_BOOL T32_;
						NI T35_;
						T32_ = (NIM_BOOL)0;
						T32_ = hasKey_DyKLR1cNLT9cYc2bz5XA9cYw(TM_KiNTuQ9alifhptBrRwE19b2A_24, name);
						if (!T32_) goto LA33_;
						T35_ = (NI)0;
						T35_ = X5BX5D__3uHbWNTgkIuCFgSUKhN19bg(TM_KiNTuQ9alifhptBrRwE19b2A_24, name);
						(*Result).Field1 = (NI)((*Result).Field1 | T35_);
					}
					goto LA23_;
					LA33_: ;
					{
						if (!eqStrings(name, ((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_34))) goto LA37_;
						(*Result).Field2 = NIM_FALSE;
					}
					goto LA23_;
					LA37_: ;
					{
						goto LA1;
					}
					LA23_: ;
					optionStart = (NI)(i + ((NI) 1));
					equals = NIM_FALSE;
				}
				goto LA4_;
				LA20_: ;
				{
					if (!!(equals)) goto LA41_;
					{
						if (!((NU8)(c) == (NU8)(61))) goto LA45_;
						equals = NIM_TRUE;
						{
							tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T49_;
							NimStringDesc* T50_;
							NIM_BOOL T51_;
							T49_ = dotdot__vDQySKWzgnxQdUarow6k5Qnre((NI)(optionStart + ((NI) 2)), i);
							T50_ = (NimStringDesc*)0;
							T50_ = X5BX5D__xiaaX9b4cczHG39bivOynT9bgnre(pattern, T49_);
							T51_ = (NIM_BOOL)0;
							T51_ = contains_jPdUhZfr9a8sH2V3ZBDljzwnre(TM_KiNTuQ9alifhptBrRwE19b2A_7, 16, T50_);
							if (!!(T51_)) goto LA52_;
							goto LA1;
						}
						LA52_: ;
					}
					goto LA43_;
					LA45_: ;
					{
						if (!!((((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)) || ((NU8)(c)) >= ((NU8)(48)) && ((NU8)(c)) <= ((NU8)(57)) || ((NU8)(c)) == ((NU8)(95))))) goto LA55_;
						goto LA1;
					}
					goto LA43_;
					LA55_: ;
					LA43_: ;
				}
				goto LA4_;
				LA41_: ;
				LA4_: ;
				i_2 += ((NI) 1);
			} LA3: ;
		}
	} LA1: ;
	T57_ = dotdot__vDQySKWzgnxQdUarow6k5Qnre(optionStart, (pattern ? (pattern->Sup.len-1) : -1));
	T58_ = (NimStringDesc*)0;
	T58_ = X5BX5D__xiaaX9b4cczHG39bivOynT9bgnre(pattern, T57_);
	(*Result).Field0 = resizeString((*Result).Field0, T58_->Sup.len + 0);
appendString((*Result).Field0, T58_);
}

N_LIB_PRIVATE N_NIMCALL(void, destroyRegex_XgDJaQTWYPopj0N33Dv15g)(tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw* pattern) {
	Dl_275691_(((NCSTRING) ((*pattern).pcreObj)));
	(*pattern).pcreObj = NIM_NIL;
	{
		if (!!(((*pattern).pcreExtra == NIM_NIL))) goto LA3_;
		Dl_275758_((*pattern).pcreExtra);
	}
	LA3_: ;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}
static N_NIMCALL(void, Marker_tyRef_4Y8poQHbErL2uzGraWOOmw)(void* p, NI op) {
	tyObject_SyntaxErrorcolonObjectType__JKyk7RuO2Y7QBAE9aLjFv9bA* a;
	a = (tyObject_SyntaxErrorcolonObjectType__JKyk7RuO2Y7QBAE9aLjFv9bA*)p;
	nimGCvisit((void*)(*a).Sup.Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.Sup.message, op);
	nimGCvisit((void*)(*a).Sup.Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.Sup.up, op);
	nimGCvisit((void*)(*a).pattern, op);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		if (!!((src == NIM_NIL))) goto LA3_;
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	(*dest) = src;
}

static N_INLINE(NIM_BOOL, eqeq__9ccNWqrTIE9bcAqE2Q0ro7zgnre)(NCSTRING x, NCSTRING y) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		if (!(((void*) (x)) == ((void*) (y)))) goto LA3_;
		result = NIM_TRUE;
	}
	goto LA1_;
	LA3_: ;
	{
		NIM_BOOL T6_;
		T6_ = (NIM_BOOL)0;
		T6_ = (x == 0);
		if (T6_) goto LA7_;
		T6_ = (y == 0);
		LA7_: ;
		if (!T6_) goto LA8_;
		result = NIM_FALSE;
	}
	goto LA1_;
	LA8_: ;
	{
		int T11_;
		T11_ = (int)0;
		T11_ = strcmp(x, y);
		result = (T11_ == ((NI32) 0));
	}
	LA1_: ;
	return result;
}
static N_NIMCALL(void, Marker_tyRef_ouvOCYwP8k3PEYE9bP5THng)(void* p, NI op) {
	tyObject_StudyErrorcolonObjectType__iukRLg9aUkCVGWqRsfNRcow* a;
	a = (tyObject_StudyErrorcolonObjectType__iukRLg9aUkCVGWqRsfNRcow*)p;
	nimGCvisit((void*)(*a).Sup.Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.Sup.message, op);
	nimGCvisit((void*)(*a).Sup.Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.Sup.up, op);
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	(*dest) = src;
}

N_LIB_PRIVATE N_NIMCALL(int, getinfo_I69cDrsTKnD5deWeuo8Hivg)(tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw* pattern, int opt) {
	int result;
	int retcode;
	result = (int)0;
	retcode = Dl_275697_((*pattern).pcreObj, (*pattern).pcreExtra, opt, ((void*) ((&result))));
	{
		tyObject_FieldError_cFRnc8M9cG1X9b9cx0eykcZfA* e;
		tyArray_Re75IspeoxXy2oCZHwcRrA T5_;
		if (!(retcode < ((NI32) 0))) goto LA3_;
		e = (tyObject_FieldError_cFRnc8M9cG1X9b9cx0eykcZfA*)0;
		e = (tyObject_FieldError_cFRnc8M9cG1X9b9cx0eykcZfA*) newObj((&NTI_UhsUhdse8ntQEMKWaJuOMw_), sizeof(tyObject_FieldError_cFRnc8M9cG1X9b9cx0eykcZfA));
		(*e).Sup.Sup.m_type = (&NTI_cFRnc8M9cG1X9b9cx0eykcZfA_);
		memset((void*)T5_, 0, sizeof(tyArray_Re75IspeoxXy2oCZHwcRrA));
		T5_[0] = nimIntToStr(((NI) (opt)));
		T5_[1] = nimIntToStr(((NI) (retcode)));
		asgnRefNoCycle((void**) (&(*e).Sup.message), nsuFormatOpenArray(((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_36), T5_, 2));
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "FieldError");
	}
	LA3_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, getinfo_m2U5mq0ZzHKP9bxvWmMXf5w)(tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw* pattern, int opt) {
	NI result;
	int retcode;
	result = (NI)0;
	retcode = Dl_275697_((*pattern).pcreObj, (*pattern).pcreExtra, opt, ((void*) ((&result))));
	{
		tyObject_FieldError_cFRnc8M9cG1X9b9cx0eykcZfA* e;
		tyArray_Re75IspeoxXy2oCZHwcRrA T5_;
		if (!(retcode < ((NI32) 0))) goto LA3_;
		e = (tyObject_FieldError_cFRnc8M9cG1X9b9cx0eykcZfA*)0;
		e = (tyObject_FieldError_cFRnc8M9cG1X9b9cx0eykcZfA*) newObj((&NTI_UhsUhdse8ntQEMKWaJuOMw_), sizeof(tyObject_FieldError_cFRnc8M9cG1X9b9cx0eykcZfA));
		(*e).Sup.Sup.m_type = (&NTI_cFRnc8M9cG1X9b9cx0eykcZfA_);
		memset((void*)T5_, 0, sizeof(tyArray_Re75IspeoxXy2oCZHwcRrA));
		T5_[0] = nimIntToStr(((NI) (opt)));
		T5_[1] = nimIntToStr(((NI) (retcode)));
		asgnRefNoCycle((void**) (&(*e).Sup.message), nsuFormatOpenArray(((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_36), T5_, 2));
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "FieldError");
	}
	LA3_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, getNameToNumberTable_ia87UBnQeDAD9bB1fS1AL9cQ)(tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw* pattern, tyObject_Table_zjMaDBasw1LnKbj11akpfw* Result) {
	int entryCount;
	int entrySize;
	NU8* table;
	NI T1_;
	genericReset((void*)Result, (&NTI_zjMaDBasw1LnKbj11akpfw_));
	entryCount = getinfo_I69cDrsTKnD5deWeuo8Hivg(pattern, ((int) 8));
	entrySize = getinfo_I69cDrsTKnD5deWeuo8Hivg(pattern, ((int) 7));
	T1_ = (NI)0;
	T1_ = getinfo_m2U5mq0ZzHKP9bxvWmMXf5w(pattern, ((int) 9));
	table = ((NU8*) (T1_));
	initTable_3Cf7Fyn7tUxJRodC9aUxtFw(((NI) 64), Result);
	{
		NI i;
		NI colontmp_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = ((NI) (entryCount));
		i_2 = ((NI) 0);
		{
			while (1) {
				NI pos;
				NI num;
				NimStringDesc* name;
				NI idx;
				if (!(i_2 < colontmp_)) goto LA4;
				i = i_2;
				pos = (NI)(i * ((NI) (entrySize)));
				num = (NI)((NI)((NU64)(((NI) (table[(pos)- 0]))) << (NU64)(((NI) 8))) | (NI)(((NI) (table[((NI)(pos + ((NI) 1)))- 0])) - ((NI) 1)));
				name = copyString(((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_6));
				idx = ((NI) 2);
				{
					while (1) {
						if (!!((table[((NI)(pos + idx))- 0] == ((NI) 0)))) goto LA6;
						name = addChar(name, ((NIM_CHAR) (table[((NI)(pos + idx))- 0])));
						idx += ((NI) 1);
					} LA6: ;
				}
				X5BX5Deq__ElMq9artIyfSkc1PsoGBTww(Result, name, num);
				i_2 += ((NI) 1);
			} LA4: ;
		}
	}
}

N_LIB_PRIVATE N_NIMCALL(tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw*, initRegex_9b7dPCPhepIsjVMqyciPoDg)(NimStringDesc* pattern, NI flags, NIM_BOOL study) {
	tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw* result;
	NimStringDesc* T1_;
	NCSTRING errorMsg;
	int errOffset;
	result = (tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw*)0;
	result = (tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw*) newObj((&NTI_b2AcSq8fDE9aZulLX3In9a7g_), sizeof(tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw));
	T1_ = (NimStringDesc*)0;
	T1_ = (*result).pattern; (*result).pattern = copyStringRC1(pattern);
	if (T1_) nimGCunrefNoCycle(T1_);
	errorMsg = (NCSTRING)0;
	errOffset = (int)0;
	(*result).pcreObj = Dl_275601_(pattern->data, ((int) (flags)), (&errorMsg), (&errOffset), NIM_NIL);
	{
		tyObject_SyntaxErrorcolonObjectType__JKyk7RuO2Y7QBAE9aLjFv9bA* T6_;
		NimStringDesc* T7_;
		if (!((*result).pcreObj == NIM_NIL)) goto LA4_;
		T6_ = (tyObject_SyntaxErrorcolonObjectType__JKyk7RuO2Y7QBAE9aLjFv9bA*)0;
		T6_ = (tyObject_SyntaxErrorcolonObjectType__JKyk7RuO2Y7QBAE9aLjFv9bA*) newObj((&NTI_4Y8poQHbErL2uzGraWOOmw_), sizeof(tyObject_SyntaxErrorcolonObjectType__JKyk7RuO2Y7QBAE9aLjFv9bA));
		(*T6_).Sup.Sup.Sup.m_type = (&NTI_JKyk7RuO2Y7QBAE9aLjFv9bA_);
		asgnRefNoCycle((void**) (&(*T6_).Sup.Sup.message), cstrToNimstr(errorMsg));
		(*T6_).pos = ((NI) (errOffset));
		T7_ = (NimStringDesc*)0;
		T7_ = (*T6_).pattern; (*T6_).pattern = copyStringRC1(pattern);
		if (T7_) nimGCunrefNoCycle(T7_);
		raiseException((Exception*)T6_, "SyntaxError:ObjectType");
	}
	LA4_: ;
	{
		int options;
		int hasJit;
		if (!study) goto LA10_;
		options = ((int) 0);
		hasJit = (int)0;
		{
			int T14_;
			T14_ = (int)0;
			T14_ = Dl_275623_(((int) 9), ((void*) ((&hasJit))));
			if (!(T14_ == ((NI32) 0))) goto LA15_;
			{
				if (!(hasJit == ((NI32) 1))) goto LA19_;
				options = ((int) 1);
			}
			LA19_: ;
		}
		LA15_: ;
		(*result).pcreExtra = Dl_275750_((*result).pcreObj, options, (&errorMsg));
		{
			NIM_BOOL T23_;
			tyObject_StudyErrorcolonObjectType__iukRLg9aUkCVGWqRsfNRcow* T26_;
			T23_ = (NIM_BOOL)0;
			T23_ = eqeq__9ccNWqrTIE9bcAqE2Q0ro7zgnre(errorMsg, NIM_NIL);
			if (!!(T23_)) goto LA24_;
			T26_ = (tyObject_StudyErrorcolonObjectType__iukRLg9aUkCVGWqRsfNRcow*)0;
			T26_ = (tyObject_StudyErrorcolonObjectType__iukRLg9aUkCVGWqRsfNRcow*) newObj((&NTI_ouvOCYwP8k3PEYE9bP5THng_), sizeof(tyObject_StudyErrorcolonObjectType__iukRLg9aUkCVGWqRsfNRcow));
			(*T26_).Sup.Sup.Sup.m_type = (&NTI_iukRLg9aUkCVGWqRsfNRcow_);
			asgnRefNoCycle((void**) (&(*T26_).Sup.Sup.message), cstrToNimstr(errorMsg));
			raiseException((Exception*)T26_, "StudyError:ObjectType");
		}
		LA24_: ;
	}
	LA10_: ;
	getNameToNumberTable_ia87UBnQeDAD9bB1fS1AL9cQ(result, (&(*result).captureNameToId));
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw*, re_5YObgtpedTBKZLpqEDsMpg)(NimStringDesc* pattern) {
	tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw* result;
	tyTuple_p49cp3DD9aai5K1o5mfF67vw T1_;
	NimStringDesc* pattern_2;
	NI flags;
	NIM_BOOL study;
	result = (tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw*)0;
	memset((void*)(&T1_), 0, sizeof(tyTuple_p49cp3DD9aai5K1o5mfF67vw));
	extractOptions_9aLyPIoKa7QTA03XJxQTIeA(pattern, (&T1_));
	pattern_2 = (NimStringDesc*)0;
	pattern_2 = T1_.Field0;
	flags = (NI)0;
	flags = T1_.Field1;
	study = (NIM_BOOL)0;
	study = T1_.Field2;
	result = initRegex_9b7dPCPhepIsjVMqyciPoDg(pattern_2, flags, study);
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_nreInit000)(void) {
nimRegisterGlobalMarker(TM_KiNTuQ9alifhptBrRwE19b2A_3);
	asgnRefNoCycle((void**) (&SpecialCharMatcher_79aI60tu0f8LeTOA0JymnBQ), re_5YObgtpedTBKZLpqEDsMpg(((NimStringDesc*) &TM_KiNTuQ9alifhptBrRwE19b2A_37)));
}

NIM_EXTERNC N_NOINLINE(void, stdlib_nreDatInit000)(void) {
static TNimNode* TM_KiNTuQ9alifhptBrRwE19b2A_2[4];
static TNimNode* TM_KiNTuQ9alifhptBrRwE19b2A_4[3];
static TNimNode* TM_KiNTuQ9alifhptBrRwE19b2A_35[2];
static TNimNode TM_KiNTuQ9alifhptBrRwE19b2A_0[14];
NTI_ULxINHgL1NYel7wmacOU9aw_.size = sizeof(tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw);
NTI_ULxINHgL1NYel7wmacOU9aw_.kind = 18;
NTI_ULxINHgL1NYel7wmacOU9aw_.base = 0;
NTI_ULxINHgL1NYel7wmacOU9aw_.flags = 2;
TM_KiNTuQ9alifhptBrRwE19b2A_2[0] = &TM_KiNTuQ9alifhptBrRwE19b2A_0[1];
TM_KiNTuQ9alifhptBrRwE19b2A_0[1].kind = 1;
TM_KiNTuQ9alifhptBrRwE19b2A_0[1].offset = offsetof(tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw, pattern);
TM_KiNTuQ9alifhptBrRwE19b2A_0[1].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_KiNTuQ9alifhptBrRwE19b2A_0[1].name = "pattern";
TM_KiNTuQ9alifhptBrRwE19b2A_2[1] = &TM_KiNTuQ9alifhptBrRwE19b2A_0[2];
TM_KiNTuQ9alifhptBrRwE19b2A_0[2].kind = 1;
TM_KiNTuQ9alifhptBrRwE19b2A_0[2].offset = offsetof(tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw, pcreObj);
TM_KiNTuQ9alifhptBrRwE19b2A_0[2].typ = (&NTI_WH9aVfHDhtZbU6Y5QgauqZQ_);
TM_KiNTuQ9alifhptBrRwE19b2A_0[2].name = "pcreObj";
TM_KiNTuQ9alifhptBrRwE19b2A_2[2] = &TM_KiNTuQ9alifhptBrRwE19b2A_0[3];
TM_KiNTuQ9alifhptBrRwE19b2A_0[3].kind = 1;
TM_KiNTuQ9alifhptBrRwE19b2A_0[3].offset = offsetof(tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw, pcreExtra);
TM_KiNTuQ9alifhptBrRwE19b2A_0[3].typ = (&NTI_z1uZWlkSdiDfd9ahW9a6Ibug_);
TM_KiNTuQ9alifhptBrRwE19b2A_0[3].name = "pcreExtra";
TM_KiNTuQ9alifhptBrRwE19b2A_2[3] = &TM_KiNTuQ9alifhptBrRwE19b2A_0[4];
TM_KiNTuQ9alifhptBrRwE19b2A_0[4].kind = 1;
TM_KiNTuQ9alifhptBrRwE19b2A_0[4].offset = offsetof(tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw, captureNameToId);
TM_KiNTuQ9alifhptBrRwE19b2A_0[4].typ = (&NTI_zjMaDBasw1LnKbj11akpfw_);
TM_KiNTuQ9alifhptBrRwE19b2A_0[4].name = "captureNameToId";
TM_KiNTuQ9alifhptBrRwE19b2A_0[0].len = 4; TM_KiNTuQ9alifhptBrRwE19b2A_0[0].kind = 2; TM_KiNTuQ9alifhptBrRwE19b2A_0[0].sons = &TM_KiNTuQ9alifhptBrRwE19b2A_2[0];
NTI_ULxINHgL1NYel7wmacOU9aw_.node = &TM_KiNTuQ9alifhptBrRwE19b2A_0[0];
NTI_b2AcSq8fDE9aZulLX3In9a7g_.size = sizeof(tyObject_RegexcolonObjectType__ULxINHgL1NYel7wmacOU9aw*);
NTI_b2AcSq8fDE9aZulLX3In9a7g_.kind = 22;
NTI_b2AcSq8fDE9aZulLX3In9a7g_.base = (&NTI_ULxINHgL1NYel7wmacOU9aw_);
NTI_b2AcSq8fDE9aZulLX3In9a7g_.flags = 2;
NTI_b2AcSq8fDE9aZulLX3In9a7g_.marker = Marker_tyRef_b2AcSq8fDE9aZulLX3In9a7g;
NTI_p49cp3DD9aai5K1o5mfF67vw_.size = sizeof(tyTuple_p49cp3DD9aai5K1o5mfF67vw);
NTI_p49cp3DD9aai5K1o5mfF67vw_.kind = 18;
NTI_p49cp3DD9aai5K1o5mfF67vw_.base = 0;
NTI_p49cp3DD9aai5K1o5mfF67vw_.flags = 2;
TM_KiNTuQ9alifhptBrRwE19b2A_4[0] = &TM_KiNTuQ9alifhptBrRwE19b2A_0[6];
TM_KiNTuQ9alifhptBrRwE19b2A_0[6].kind = 1;
TM_KiNTuQ9alifhptBrRwE19b2A_0[6].offset = offsetof(tyTuple_p49cp3DD9aai5K1o5mfF67vw, Field0);
TM_KiNTuQ9alifhptBrRwE19b2A_0[6].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_KiNTuQ9alifhptBrRwE19b2A_0[6].name = "Field0";
TM_KiNTuQ9alifhptBrRwE19b2A_4[1] = &TM_KiNTuQ9alifhptBrRwE19b2A_0[7];
TM_KiNTuQ9alifhptBrRwE19b2A_0[7].kind = 1;
TM_KiNTuQ9alifhptBrRwE19b2A_0[7].offset = offsetof(tyTuple_p49cp3DD9aai5K1o5mfF67vw, Field1);
TM_KiNTuQ9alifhptBrRwE19b2A_0[7].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_KiNTuQ9alifhptBrRwE19b2A_0[7].name = "Field1";
TM_KiNTuQ9alifhptBrRwE19b2A_4[2] = &TM_KiNTuQ9alifhptBrRwE19b2A_0[8];
TM_KiNTuQ9alifhptBrRwE19b2A_0[8].kind = 1;
TM_KiNTuQ9alifhptBrRwE19b2A_0[8].offset = offsetof(tyTuple_p49cp3DD9aai5K1o5mfF67vw, Field2);
TM_KiNTuQ9alifhptBrRwE19b2A_0[8].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_KiNTuQ9alifhptBrRwE19b2A_0[8].name = "Field2";
TM_KiNTuQ9alifhptBrRwE19b2A_0[5].len = 3; TM_KiNTuQ9alifhptBrRwE19b2A_0[5].kind = 2; TM_KiNTuQ9alifhptBrRwE19b2A_0[5].sons = &TM_KiNTuQ9alifhptBrRwE19b2A_4[0];
NTI_p49cp3DD9aai5K1o5mfF67vw_.node = &TM_KiNTuQ9alifhptBrRwE19b2A_0[5];
(&NTI_b2AcSq8fDE9aZulLX3In9a7g_)->finalizer = (void*)destroyRegex_XgDJaQTWYPopj0N33Dv15g;
NTI_GpPe019cJO4uVSU1kDvvJdQ_.size = sizeof(tyObject_RegexErrorcolonObjectType__GpPe019cJO4uVSU1kDvvJdQ);
NTI_GpPe019cJO4uVSU1kDvvJdQ_.kind = 17;
NTI_GpPe019cJO4uVSU1kDvvJdQ_.base = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
TM_KiNTuQ9alifhptBrRwE19b2A_0[9].len = 0; TM_KiNTuQ9alifhptBrRwE19b2A_0[9].kind = 2;
NTI_GpPe019cJO4uVSU1kDvvJdQ_.node = &TM_KiNTuQ9alifhptBrRwE19b2A_0[9];
NTI_JKyk7RuO2Y7QBAE9aLjFv9bA_.size = sizeof(tyObject_SyntaxErrorcolonObjectType__JKyk7RuO2Y7QBAE9aLjFv9bA);
NTI_JKyk7RuO2Y7QBAE9aLjFv9bA_.kind = 17;
NTI_JKyk7RuO2Y7QBAE9aLjFv9bA_.base = (&NTI_GpPe019cJO4uVSU1kDvvJdQ_);
TM_KiNTuQ9alifhptBrRwE19b2A_35[0] = &TM_KiNTuQ9alifhptBrRwE19b2A_0[11];
TM_KiNTuQ9alifhptBrRwE19b2A_0[11].kind = 1;
TM_KiNTuQ9alifhptBrRwE19b2A_0[11].offset = offsetof(tyObject_SyntaxErrorcolonObjectType__JKyk7RuO2Y7QBAE9aLjFv9bA, pos);
TM_KiNTuQ9alifhptBrRwE19b2A_0[11].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_KiNTuQ9alifhptBrRwE19b2A_0[11].name = "pos";
TM_KiNTuQ9alifhptBrRwE19b2A_35[1] = &TM_KiNTuQ9alifhptBrRwE19b2A_0[12];
TM_KiNTuQ9alifhptBrRwE19b2A_0[12].kind = 1;
TM_KiNTuQ9alifhptBrRwE19b2A_0[12].offset = offsetof(tyObject_SyntaxErrorcolonObjectType__JKyk7RuO2Y7QBAE9aLjFv9bA, pattern);
TM_KiNTuQ9alifhptBrRwE19b2A_0[12].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_KiNTuQ9alifhptBrRwE19b2A_0[12].name = "pattern";
TM_KiNTuQ9alifhptBrRwE19b2A_0[10].len = 2; TM_KiNTuQ9alifhptBrRwE19b2A_0[10].kind = 2; TM_KiNTuQ9alifhptBrRwE19b2A_0[10].sons = &TM_KiNTuQ9alifhptBrRwE19b2A_35[0];
NTI_JKyk7RuO2Y7QBAE9aLjFv9bA_.node = &TM_KiNTuQ9alifhptBrRwE19b2A_0[10];
NTI_4Y8poQHbErL2uzGraWOOmw_.size = sizeof(tyObject_SyntaxErrorcolonObjectType__JKyk7RuO2Y7QBAE9aLjFv9bA*);
NTI_4Y8poQHbErL2uzGraWOOmw_.kind = 22;
NTI_4Y8poQHbErL2uzGraWOOmw_.base = (&NTI_JKyk7RuO2Y7QBAE9aLjFv9bA_);
NTI_4Y8poQHbErL2uzGraWOOmw_.marker = Marker_tyRef_4Y8poQHbErL2uzGraWOOmw;
NTI_iukRLg9aUkCVGWqRsfNRcow_.size = sizeof(tyObject_StudyErrorcolonObjectType__iukRLg9aUkCVGWqRsfNRcow);
NTI_iukRLg9aUkCVGWqRsfNRcow_.kind = 17;
NTI_iukRLg9aUkCVGWqRsfNRcow_.base = (&NTI_GpPe019cJO4uVSU1kDvvJdQ_);
TM_KiNTuQ9alifhptBrRwE19b2A_0[13].len = 0; TM_KiNTuQ9alifhptBrRwE19b2A_0[13].kind = 2;
NTI_iukRLg9aUkCVGWqRsfNRcow_.node = &TM_KiNTuQ9alifhptBrRwE19b2A_0[13];
NTI_ouvOCYwP8k3PEYE9bP5THng_.size = sizeof(tyObject_StudyErrorcolonObjectType__iukRLg9aUkCVGWqRsfNRcow*);
NTI_ouvOCYwP8k3PEYE9bP5THng_.kind = 22;
NTI_ouvOCYwP8k3PEYE9bP5THng_.base = (&NTI_iukRLg9aUkCVGWqRsfNRcow_);
NTI_ouvOCYwP8k3PEYE9bP5THng_.marker = Marker_tyRef_ouvOCYwP8k3PEYE9bP5THng;
}

