/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#include <sys/ioctl.h>
#include <fcntl.h>
#include <unistd.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_IOctl_WinSize_pb6i9aLcdojBXEMqdEzDkSA tyObject_IOctl_WinSize_pb6i9aLcdojBXEMqdEzDkSA;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct tyObject_IOctl_WinSize_pb6i9aLcdojBXEMqdEzDkSA {
unsigned short ws_row;
unsigned short ws_col;
unsigned short ws_xpixel;
unsigned short ws_ypixel;
};
typedef NI tyArray_Bd4h7Ocx9bGTvrKzPIWNlHw[3];
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NI tyArray_GAcaPw08Gj9cXYhAaMMr9cfw[1];
N_LIB_PRIVATE N_NIMCALL(NI, terminalWidthIoctl_u2BBS9b3k8WyoyVOocOs5YQ)(NI* fds, NI fdsLen_0);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getEnv_9b1nh9cAHhSLlHOPz8lCk5FA)(NimStringDesc* key, NimStringDesc* default_0);
N_LIB_PRIVATE N_NIMCALL(NI, npuParseInt)(NimStringDesc* s, NI* number, NI start);
NIM_BOOL trueColorIsSupported_kn9b0UIbK9cVbUGz9cl7kNkkw;
NIM_BOOL trueColorIsEnabled_Y9c1UaDywi8o8DHl8VRJG9cQ;
NIM_BOOL fgSetColor_az9a3BILKewIOic9a2Ah9a4tQ;
NIM_THREADVAR NI gFG_g7w4T3anr20OMlWloNx2tQ;
NIM_THREADVAR NI gBG_dgmeknpHWrtwqMJGQAp9atA;
NIM_CONST tyArray_Bd4h7Ocx9bGTvrKzPIWNlHw TM_CN3raB9atujkEiPpxYAdlgQ_2 = {((NI) 0),
((NI) 1),
((NI) 2)}
;
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_3, "COLUMNS", 7);
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_4, "", 0);

N_LIB_PRIVATE N_NIMCALL(NI, terminalWidthIoctl_u2BBS9b3k8WyoyVOocOs5YQ)(NI* fds, NI fdsLen_0) {
	NI result;
	tyObject_IOctl_WinSize_pb6i9aLcdojBXEMqdEzDkSA win;
{	result = (NI)0;
	memset((void*)(&win), 0, sizeof(win));
	{
		NI fd;
		NI i;
		fd = (NI)0;
		i = ((NI) 0);
		{
			while (1) {
				if (!(i < fdsLen_0)) goto LA3;
				fd = fds[i];
				{
					NI T6_;
					T6_ = (NI)0;
					T6_ = ioctl(((int) (fd)), TIOCGWINSZ, (&win));
					if (!!((T6_ == ((NI) -1)))) goto LA7_;
					result = ((NI) (win.ws_col));
					goto BeforeRet_;
				}
				LA7_: ;
				i += ((NI) 1);
			} LA3: ;
		}
	}
	result = ((NI) 0);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, terminalWidth_Tjr5MOdj42hdx5sjNUiDXw)(void) {
	NI result;
	NI w;
	NimStringDesc* cterm;
	int fd;
	NCSTRING T5_;
	int T11_;
	NimStringDesc* s;
{	result = (NI)0;
	w = terminalWidthIoctl_u2BBS9b3k8WyoyVOocOs5YQ(TM_CN3raB9atujkEiPpxYAdlgQ_2, 3);
	{
		if (!(((NI) 0) < w)) goto LA3_;
		result = w;
		goto BeforeRet_;
	}
	LA3_: ;
	cterm = mnewString(((NI) (L_ctermid)));
	T5_ = (NCSTRING)0;
	T5_ = ctermid(cterm->data);
	fd = open(T5_, O_RDONLY);
	{
		tyArray_GAcaPw08Gj9cXYhAaMMr9cfw T10_;
		if (!!((fd == ((NI32) -1)))) goto LA8_;
		T10_[0] = ((NI) (fd));
		w = terminalWidthIoctl_u2BBS9b3k8WyoyVOocOs5YQ(T10_, 1);
	}
	LA8_: ;
	T11_ = (int)0;
	T11_ = close(fd);
	T11_;
	{
		if (!(((NI) 0) < w)) goto LA14_;
		result = w;
		goto BeforeRet_;
	}
	LA14_: ;
	s = getEnv_9b1nh9cAHhSLlHOPz8lCk5FA(((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_3), ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_4));
	{
		NIM_BOOL T18_;
		NIM_BOOL T19_;
		NI T21_;
		T18_ = (NIM_BOOL)0;
		T19_ = (NIM_BOOL)0;
		T19_ = (((NI) 0) < (s ? s->Sup.len : 0));
		if (!(T19_)) goto LA20_;
		T21_ = (NI)0;
		T21_ = npuParseInt(s, (&w), ((NI) 0));
		T19_ = (((NI) 0) < T21_);
		LA20_: ;
		T18_ = T19_;
		if (!(T18_)) goto LA22_;
		T18_ = (((NI) 0) < w);
		LA22_: ;
		if (!T18_) goto LA23_;
		result = w;
		goto BeforeRet_;
	}
	LA23_: ;
	result = ((NI) 80);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_terminalInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_terminalDatInit000)(void) {
}

