/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <windows.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix

N_LIB_PRIVATE N_NIMCALL(void, acquire_9bBEZeGCRkWQl9bLT1qt423Q)(CRITICAL_SECTION* lock) {
	EnterCriticalSection(lock);
}

N_LIB_PRIVATE N_NIMCALL(void, release_9bBEZeGCRkWQl9bLT1qt423Q_2)(CRITICAL_SECTION* lock) {
	LeaveCriticalSection(lock);
}
NIM_EXTERNC N_NOINLINE(void, stdlib_locksInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_locksDatInit000)(void) {
}

