/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <windows.h>
#include <string.h>
#include <time.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_GcThread_hgJQSlfXDOK3SwSHjeZBXg tyObject_GcThread_hgJQSlfXDOK3SwSHjeZBXg;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw;
typedef struct tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw;
typedef struct tyObject_IndexError_b0IIwghFQBADkB2c86kXQA tyObject_IndexError_b0IIwghFQBADkB2c86kXQA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyTuple_7q7q3E6Oj24ZNVJb9aonhAg tyTuple_7q7q3E6Oj24ZNVJb9aonhAg;
typedef struct tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ;
typedef struct tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg;
typedef struct tyObject_WIN32_FIND_DATA_aYwmSz9bIz0JHAL9ciwIrnhA tyObject_WIN32_FIND_DATA_aYwmSz9bIz0JHAL9ciwIrnhA;
typedef struct tyObject_FILETIME_bs4NMleDDVF7xsEK0SGLBw tyObject_FILETIME_bs4NMleDDVF7xsEK0SGLBw;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tySequence_WF89a8QyKeDCh4DYWTmSiBg tySequence_WF89a8QyKeDCh4DYWTmSiBg;
typedef struct TSafePoint TSafePoint;
typedef struct GcFrameHeader GcFrameHeader;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NF tyArray_iV2wVpdhi9coq9cstlcqapXg[2001];
struct tyObject_GcThread_hgJQSlfXDOK3SwSHjeZBXg {
tyArray_iV2wVpdhi9coq9cstlcqapXg tls;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw {
tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* head;
tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* tail;
CRITICAL_SECTION lock;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw toDispose;
NI gcThreadId;
};
typedef N_STDCALL_PTR(NI16*, tyProc_9cu0cWy2jNXKVhds9cs4T9a9cA) (void);
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_IndexError_b0IIwghFQBADkB2c86kXQA {
  Exception Sup;
};
typedef N_STDCALL_PTR(NI32, tyProc_hayl9b1HhJokJ1Zo9ctoglPg) (NI16* lpFileName);
typedef N_STDCALL_PTR(NI32, tyProc_M3PxDlueeoWgT3BgpzrqYw) (NI handle, NI16* buf, NI32 size);
struct tyTuple_7q7q3E6Oj24ZNVJb9aonhAg {
NimStringDesc* Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
};
typedef N_STDCALL_PTR(NI32, tyProc_9aKTqJQ9a3bUAymphQdhIjZg) (NI16* lpFileName, NI32 nBufferLength, NI16* lpBuffer, NI16** lpFilePart);
typedef N_STDCALL_PTR(NI32, tyProc_5sM6DjmSDLuKbGFwf0KfoA) (NI16* pathName, void* security);
typedef N_STDCALL_PTR(NI32, tyProc_9bXer9a4ps9aSGctILcxWReVw) (void);
struct tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg {
  Exception Sup;
};
struct tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ {
  tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg Sup;
};
struct tyObject_FILETIME_bs4NMleDDVF7xsEK0SGLBw {
NI32 dwLowDateTime;
NI32 dwHighDateTime;
};
typedef NI16 tyArray_EKfNt9b8uxndgFbu2Ky3XAQ[260];
typedef NI16 tyArray_Get9cpRTS5VjGKP6CDsI9bYA[14];
struct tyObject_WIN32_FIND_DATA_aYwmSz9bIz0JHAL9ciwIrnhA {
NI32 dwFileAttributes;
tyObject_FILETIME_bs4NMleDDVF7xsEK0SGLBw ftCreationTime;
tyObject_FILETIME_bs4NMleDDVF7xsEK0SGLBw ftLastAccessTime;
tyObject_FILETIME_bs4NMleDDVF7xsEK0SGLBw ftLastWriteTime;
NI32 nFileSizeHigh;
NI32 nFileSizeLow;
NI32 dwReserved0;
NI32 dwReserved1;
tyArray_EKfNt9b8uxndgFbu2Ky3XAQ cFileName;
tyArray_Get9cpRTS5VjGKP6CDsI9bYA cAlternateFileName;
};
typedef N_STDCALL_PTR(NI, tyProc_RG83qWQtsxfLxD7HYoLyfA) (NI16* lpFileName, tyObject_WIN32_FIND_DATA_aYwmSz9bIz0JHAL9ciwIrnhA* lpFindFileData);
typedef N_STDCALL_PTR(void, tyProc_ofoySXaAAlxxs9bQS9a1etlg) (NI hFindFile);
typedef N_STDCALL_PTR(void, tyProc_Tjolzh1w2dIIpj3oCDGPFw) (NI32 dwMilliseconds);
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
typedef void* tyArray_Rrw59cMvNu8cDA9cQDh4v2oA[100];
struct tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw {
tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* next;
NI dataLen;
tyArray_Rrw59cMvNu8cDA9cQDh4v2oA d;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc_hgOQFBQi19biNdOUUkFOOxA) (Exception* e);
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc_IIomJ6ptE6vfJ5zRbATgkQ;
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
struct tySequence_WF89a8QyKeDCh4DYWTmSiBg {
  TGenericSeq Sup;
  tyProc_IIomJ6ptE6vfJ5zRbATgkQ data[SEQ_DECL_SIZE];
};
typedef struct {tyProc_hgOQFBQi19biNdOUUkFOOxA localRaiseHook_EIvMhANBvB9cp2Ezvt29cADg;
tySequence_WF89a8QyKeDCh4DYWTmSiBg* threadDestructionHandlers_8OmU3x0fNdA0DLtOmU3kWw;
NI threadId_wzrdPYhtL9czkCWS4o9an9cRw;
TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
Exception* currException_9bVPeDJlYTi9bQApZpfH8wjg;
GcFrameHeader* gcFramePtr_ot48iojqko9aFxGhyjjjVaA;
tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
NIM_BOOL envComputed_OC1kQm9aRvX8VnmaXglp57Q;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* environment_rnCB7Cc69bd2mlM49cn9czO2Q;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* ownArgv_WVJ54JSHy7VxacV39bwBPFA;
} NimThreadVars;
static N_INLINE(void*, GetThreadLocalVars)(void);
N_LIB_PRIVATE N_NIMCALL(void*, threadVarGetValue_RA7AnSIB7ATZq3Th1d9czYg)(NI32 dwTlsIndex);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_yu6cxgKBBXbNsTkT9cyMd4g_2)(void);
N_NIMCALL(void, nimRegisterThreadLocalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NIMCALL(NI, nosparamCount)(void);
N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, nosparseCmdLine)(NimStringDesc* c);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__D2o4ABrO3iHTudww2CqX4w)(NI16* s);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nosparamStr)(NI i);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_LIB_PRIVATE N_NIMCALL(NI16*, newWideCString_keidLK9c3HkgArW69bcHZYGA)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(void, nossplitFile)(NimStringDesc* path, tyTuple_7q7q3E6Oj24ZNVJb9aonhAg* Result);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nosgetAppFilename)(void);
N_LIB_PRIVATE N_NIMCALL(NI16*, newWideCString_q1KqU6WAugdPW0cwGMbUug)(NCSTRING source, NI L);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__ll2s2AIM0tZVMtCCHxSjcQ)(NI16* w, NI estimate, NI replacement);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError_bEwAamo1N7TKcaU9akpiyIg)(NI32 errorCode, NimStringDesc* additionalInfo);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError_9bdZBDTfBOjOcVVodbA2otw)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosisAbsolute)(NimStringDesc* path);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, existsOrCreateDir_45Xwkpg5BatjRqUBSXvMTQ)(NimStringDesc* dir);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, rawCreateDir_45Xwkpg5BatjRqUBSXvMTQ_2)(NimStringDesc* dir);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosexistsDir)(NimStringDesc* dir);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(NIM_CHAR, X5BX5D__OfW9cXEAVaB9aahBBWfdc49cgbuild)(NimStringDesc* s, NI i);
N_LIB_PRIVATE N_NIMCALL(NI64, ntDiffTime)(NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(NI64, nosgetLastModificationTime)(NimStringDesc* file);
N_LIB_PRIVATE N_NIMCALL(NI, findFirstFile_9cPKjuaUWDYlrzWunhDgNng)(NimStringDesc* a, tyObject_WIN32_FIND_DATA_aYwmSz9bIz0JHAL9ciwIrnhA* b);
N_LIB_PRIVATE N_NIMCALL(NI64, fromUnix_C77WZNbbZYep1XVMN2QCfA)(NI64 unix);
N_LIB_PRIVATE N_NIMCALL(NI64, winTimeToUnixTime_0MF1tc32ZEJI7wo2ukv7DQ)(NI64 time_0);
N_LIB_PRIVATE N_NIMCALL(NI64, rdFileTime_8xfVp1z4bc5fRCRgoEFhIQ)(tyObject_FILETIME_bs4NMleDDVF7xsEK0SGLBw f);
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
extern NI32 globalsSlot_ciXDZu9c27pHpCRMoz4RIgw;
extern tyProc_9cu0cWy2jNXKVhds9cs4T9a9cA Dl_221437_;
extern TNimType NTI_z58cIdR0vOibqJ0QwYvB3Q_;
extern TNimType NTI_b0IIwghFQBADkB2c86kXQA_;
extern tyProc_hayl9b1HhJokJ1Zo9ctoglPg Dl_221411_;
extern tyProc_M3PxDlueeoWgT3BgpzrqYw Dl_220822_;
extern tyProc_9aKTqJQ9a3bUAymphQdhIjZg Dl_221404_;
extern tyProc_5sM6DjmSDLuKbGFwf0KfoA Dl_220811_;
extern tyProc_9bXer9a4ps9aSGctILcxWReVw Dl_220630_;
extern TNimType NTI_HX2M9cQhE3jaovp9aYJDdslA_;
extern TNimType NTI_9czoZw3pzPyrBmb5zTHY1OQ_;
extern tyProc_RG83qWQtsxfLxD7HYoLyfA Dl_221237_;
extern tyProc_ofoySXaAAlxxs9bQS9a1etlg Dl_221401_;
extern tyProc_Tjolzh1w2dIIpj3oCDGPFw Dl_221629_;
STRING_LITERAL(TM_yu6cxgKBBXbNsTkT9cyMd4g_3, "", 0);
STRING_LITERAL(TM_yu6cxgKBBXbNsTkT9cyMd4g_4, "invalid index", 13);
STRING_LITERAL(TM_yu6cxgKBBXbNsTkT9cyMd4g_5, "Failed to create the directory", 30);

static N_INLINE(void*, GetThreadLocalVars)(void) {
	void* result;
	void* T1_;
	result = (void*)0;
	T1_ = (void*)0;
	T1_ = threadVarGetValue_RA7AnSIB7ATZq3Th1d9czYg(globalsSlot_ciXDZu9c27pHpCRMoz4RIgw);
	result = ((void*) ((*((tyObject_GcThread_hgJQSlfXDOK3SwSHjeZBXg*) (T1_))).tls));
	return result;
}
static N_NIMCALL(void, TM_yu6cxgKBBXbNsTkT9cyMd4g_2)(void) {
	NimThreadVars* NimTV_;
	NimTV_ = (NimThreadVars*) GetThreadLocalVars();
	nimGCvisit((void*)NimTV_->ownArgv_WVJ54JSHy7VxacV39bwBPFA, 0);
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	NimThreadVars* NimTV_;
	NimTV_ = (NimThreadVars*) GetThreadLocalVars();
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&NimTV_->gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, nosparseCmdLine)(NimStringDesc* c) {
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* result;
	NI i;
	NimStringDesc* a;
	result = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	result = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
	i = ((NI) 0);
	a = copyString(((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_3));
	{
		while (1) {
			NIM_BOOL inQuote;
			NI T49_;
			NimStringDesc* T50_;
			a = setLengthStr(a, ((NI) 0));
			{
				while (1) {
					NIM_BOOL T5_;
					NIM_BOOL T6_;
					NIM_BOOL T7_;
					T5_ = (NIM_BOOL)0;
					T6_ = (NIM_BOOL)0;
					T7_ = (NIM_BOOL)0;
					T7_ = ((NU8)(c->data[i]) == (NU8)(32));
					if (T7_) goto LA8_;
					T7_ = ((NU8)(c->data[i]) == (NU8)(9));
					LA8_: ;
					T6_ = T7_;
					if (T6_) goto LA9_;
					T6_ = ((NU8)(c->data[i]) == (NU8)(10));
					LA9_: ;
					T5_ = T6_;
					if (T5_) goto LA10_;
					T5_ = ((NU8)(c->data[i]) == (NU8)(13));
					LA10_: ;
					if (!T5_) goto LA4;
					i += ((NI) 1);
				} LA4: ;
			}
			{
				if (!((NU8)(c->data[i]) == (NU8)(0))) goto LA13_;
				goto LA1;
			}
			LA13_: ;
			inQuote = NIM_FALSE;
			{
				while (1) {
					switch (((NU8)(c->data[i]))) {
					case 0:
					{
						goto LA15;
					}
					break;
					case 92:
					{
						NI j;
						j = i;
						{
							while (1) {
								if (!((NU8)(c->data[j]) == (NU8)(92))) goto LA20;
								j += ((NI) 1);
							} LA20: ;
						}
						{
							if (!((NU8)(c->data[j]) == (NU8)(34))) goto LA23_;
							{
								NI k;
								NI colontmp_;
								NI res;
								k = (NI)0;
								colontmp_ = (NI)0;
								colontmp_ = (NI)((NI)(j - i) / ((NI) 2));
								res = ((NI) 1);
								{
									while (1) {
										if (!(res <= colontmp_)) goto LA27;
										k = res;
										a = addChar(a, 92);
										res += ((NI) 1);
									} LA27: ;
								}
							}
							{
								if (!((NI)((NI)(j - i) % ((NI) 2)) == ((NI) 0))) goto LA30_;
								i = j;
							}
							goto LA28_;
							LA30_: ;
							{
								a = addChar(a, 34);
								i = (NI)(j + ((NI) 1));
							}
							LA28_: ;
						}
						goto LA21_;
						LA23_: ;
						{
							a = addChar(a, c->data[i]);
							i += ((NI) 1);
						}
						LA21_: ;
					}
					break;
					case 34:
					{
						i += ((NI) 1);
						{
							if (!!(inQuote)) goto LA37_;
							inQuote = NIM_TRUE;
						}
						goto LA35_;
						LA37_: ;
						{
							if (!((NU8)(c->data[i]) == (NU8)(34))) goto LA40_;
							a = addChar(a, c->data[i]);
							i += ((NI) 1);
						}
						goto LA35_;
						LA40_: ;
						{
							inQuote = NIM_FALSE;
							goto LA15;
						}
						LA35_: ;
					}
					break;
					case 32:
					case 9:
					{
						{
							if (!!(inQuote)) goto LA46_;
							goto LA15;
						}
						LA46_: ;
						a = addChar(a, c->data[i]);
						i += ((NI) 1);
					}
					break;
					default:
					{
						a = addChar(a, c->data[i]);
						i += ((NI) 1);
					}
					break;
					}
				}
			} LA15: ;
			result = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&(result)->Sup, sizeof(NimStringDesc*));
			T49_ = result->Sup.len++;
			T50_ = (NimStringDesc*)0;
			T50_ = result->data[T49_]; result->data[T49_] = copyStringRC1(a);
			if (T50_) nimGCunrefNoCycle(T50_);
		}
	} LA1: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, nosparamCount)(void) {
	NI result;
	NimThreadVars* NimTV_;
	NI T7_;
	NimTV_ = (NimThreadVars*) GetThreadLocalVars();
	result = (NI)0;
	{
		NI16* T5_;
		NimStringDesc* T6_;
		if (!(NimTV_->ownArgv_WVJ54JSHy7VxacV39bwBPFA == 0)) goto LA3_;
		T5_ = (NI16*)0;
		T5_ = Dl_221437_();
		T6_ = (NimStringDesc*)0;
		T6_ = dollar__D2o4ABrO3iHTudww2CqX4w(T5_);
		unsureAsgnRef((void**) (&NimTV_->ownArgv_WVJ54JSHy7VxacV39bwBPFA), nosparseCmdLine(T6_));
	}
	LA3_: ;
	T7_ = (NimTV_->ownArgv_WVJ54JSHy7VxacV39bwBPFA ? NimTV_->ownArgv_WVJ54JSHy7VxacV39bwBPFA->Sup.len : 0);
	result = (NI)(T7_ - ((NI) 1));
	return result;
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	(*dest) = src;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nosparamStr)(NI i) {
	NimStringDesc* result;
	NimThreadVars* NimTV_;
	tyObject_IndexError_b0IIwghFQBADkB2c86kXQA* e;
	NimStringDesc* T14_;
{	NimTV_ = (NimThreadVars*) GetThreadLocalVars();
	result = (NimStringDesc*)0;
	{
		NI16* T5_;
		NimStringDesc* T6_;
		if (!(NimTV_->ownArgv_WVJ54JSHy7VxacV39bwBPFA == 0)) goto LA3_;
		T5_ = (NI16*)0;
		T5_ = Dl_221437_();
		T6_ = (NimStringDesc*)0;
		T6_ = dollar__D2o4ABrO3iHTudww2CqX4w(T5_);
		unsureAsgnRef((void**) (&NimTV_->ownArgv_WVJ54JSHy7VxacV39bwBPFA), nosparseCmdLine(T6_));
	}
	LA3_: ;
	{
		NIM_BOOL T9_;
		NI T10_;
		T9_ = (NIM_BOOL)0;
		T10_ = (NimTV_->ownArgv_WVJ54JSHy7VxacV39bwBPFA ? NimTV_->ownArgv_WVJ54JSHy7VxacV39bwBPFA->Sup.len : 0);
		T9_ = (i < T10_);
		if (!(T9_)) goto LA11_;
		T9_ = (((NI) 0) <= i);
		LA11_: ;
		if (!T9_) goto LA12_;
		result = copyString(NimTV_->ownArgv_WVJ54JSHy7VxacV39bwBPFA->data[i]);
		goto BeforeRet_;
	}
	LA12_: ;
	e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*)0;
	e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*) newObj((&NTI_z58cIdR0vOibqJ0QwYvB3Q_), sizeof(tyObject_IndexError_b0IIwghFQBADkB2c86kXQA));
	(*e).Sup.Sup.m_type = (&NTI_b0IIwghFQBADkB2c86kXQA_);
	T14_ = (NimStringDesc*)0;
	T14_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_4));
	if (T14_) nimGCunrefNoCycle(T14_);
	asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
	raiseException((Exception*)e, "IndexError");
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, commandLineParams_WoBZMy8AVRATRE9bQuYWzCQ)(void) {
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* result;
	result = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	result = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = nosparamCount();
		res = ((NI) 1);
		{
			while (1) {
				NimStringDesc* T4_;
				NI T5_;
				NimStringDesc* T6_;
				if (!(res <= colontmp_)) goto LA3;
				i = res;
				T4_ = (NimStringDesc*)0;
				T4_ = nosparamStr(i);
				result = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&(result)->Sup, sizeof(NimStringDesc*));
				T5_ = result->Sup.len++;
				T6_ = (NimStringDesc*)0;
				T6_ = result->data[T5_]; result->data[T5_] = copyStringRC1(T4_);
				if (T6_) nimGCunrefNoCycle(T6_);
				res += ((NI) 1);
			} LA3: ;
		}
	}
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosexistsFile)(NimStringDesc* filename) {
	NIM_BOOL result;
	NI32 a;
	NI16* T1_;
	result = (NIM_BOOL)0;
	T1_ = (NI16*)0;
	T1_ = newWideCString_keidLK9c3HkgArW69bcHZYGA(filename);
	a = Dl_221411_(T1_);
	{
		if (!!((a == ((NI32) -1)))) goto LA4_;
		result = ((NI32)(a & ((NI32) 16)) == ((NI32) 0));
	}
	LA4_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nosgetAppFilename)(void) {
	NimStringDesc* result;
	NI32 bufsize;
	NI16* buf;
	result = (NimStringDesc*)0;
	bufsize = ((NI32) 260);
	buf = newWideCString_q1KqU6WAugdPW0cwGMbUug("", ((NI) (bufsize)));
	{
		while (1) {
			NI32 L;
			L = Dl_220822_(((NI) 0), buf, bufsize);
			{
				if (!(L == ((NI32) 0))) goto LA5_;
				result = copyString(((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_3));
				goto LA1;
			}
			goto LA3_;
			LA5_: ;
			{
				if (!(bufsize < L)) goto LA8_;
				buf = newWideCString_q1KqU6WAugdPW0cwGMbUug("", ((NI) (L)));
				bufsize = L;
			}
			goto LA3_;
			LA8_: ;
			{
				result = dollar__ll2s2AIM0tZVMtCCHxSjcQ(buf, ((NI) (L)), ((NI) 65533));
				goto LA1;
			}
			LA3_: ;
		}
	} LA1: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nosgetAppDir)(void) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	tyTuple_7q7q3E6Oj24ZNVJb9aonhAg T2_;
	result = (NimStringDesc*)0;
	T1_ = (NimStringDesc*)0;
	T1_ = nosgetAppFilename();
	memset((void*)(&T2_), 0, sizeof(T2_));
	nossplitFile(T1_, (&T2_));
	result = copyString(T2_.Field0);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nosexpandFilename)(NimStringDesc* filename) {
	NimStringDesc* result;
	NI32 bufsize;
	NI16* unused;
	NI16* res;
	result = (NimStringDesc*)0;
	bufsize = ((NI32) 260);
	unused = NIM_NIL;
	res = newWideCString_q1KqU6WAugdPW0cwGMbUug("", ((NI) (bufsize)));
	{
		while (1) {
			NI32 L;
			NI16* T3_;
			T3_ = (NI16*)0;
			T3_ = newWideCString_keidLK9c3HkgArW69bcHZYGA(filename);
			L = Dl_221404_(T3_, bufsize, res, &unused);
			{
				NI32 T8_;
				if (!(L == ((NI32) 0))) goto LA6_;
				T8_ = (NI32)0;
				T8_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
				raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T8_, ((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_3));
			}
			goto LA4_;
			LA6_: ;
			{
				if (!(bufsize < L)) goto LA10_;
				res = newWideCString_q1KqU6WAugdPW0cwGMbUug("", ((NI) (L)));
				bufsize = L;
			}
			goto LA4_;
			LA10_: ;
			{
				result = dollar__ll2s2AIM0tZVMtCCHxSjcQ(res, ((NI) (L)), ((NI) 65533));
				goto LA1;
			}
			LA4_: ;
		}
	} LA1: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, rawCreateDir_45Xwkpg5BatjRqUBSXvMTQ_2)(NimStringDesc* dir) {
	NIM_BOOL result;
	NI32 res;
	NI16* T1_;
	result = (NIM_BOOL)0;
	T1_ = (NI16*)0;
	T1_ = newWideCString_keidLK9c3HkgArW69bcHZYGA(dir);
	res = Dl_220811_(T1_, NIM_NIL);
	{
		if (!!((res == ((NI32) 0)))) goto LA4_;
		result = NIM_TRUE;
	}
	goto LA2_;
	LA4_: ;
	{
		NI32 T7_;
		T7_ = (NI32)0;
		T7_ = Dl_220630_();
		if (!(T7_ == ((NI32) 183))) goto LA8_;
		result = NIM_FALSE;
	}
	goto LA2_;
	LA8_: ;
	{
		NI32 T11_;
		T11_ = (NI32)0;
		T11_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T11_, ((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_3));
	}
	LA2_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosexistsDir)(NimStringDesc* dir) {
	NIM_BOOL result;
	NI32 a;
	NI16* T1_;
	result = (NIM_BOOL)0;
	T1_ = (NI16*)0;
	T1_ = newWideCString_keidLK9c3HkgArW69bcHZYGA(dir);
	a = Dl_221411_(T1_);
	{
		if (!!((a == ((NI32) -1)))) goto LA4_;
		result = !(((NI32)(a & ((NI32) 16)) == ((NI32) 0)));
	}
	LA4_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, existsOrCreateDir_45Xwkpg5BatjRqUBSXvMTQ)(NimStringDesc* dir) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	result = (NIM_BOOL)0;
	T1_ = (NIM_BOOL)0;
	T1_ = rawCreateDir_45Xwkpg5BatjRqUBSXvMTQ_2(dir);
	result = !(T1_);
	{
		if (!result) goto LA4_;
		{
			NIM_BOOL T8_;
			tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ* e;
			NimStringDesc* T11_;
			T8_ = (NIM_BOOL)0;
			T8_ = nosexistsDir(dir);
			if (!!(T8_)) goto LA9_;
			e = (tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ*)0;
			e = (tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ*) newObj((&NTI_HX2M9cQhE3jaovp9aYJDdslA_), sizeof(tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ));
			(*e).Sup.Sup.Sup.m_type = (&NTI_9czoZw3pzPyrBmb5zTHY1OQ_);
			T11_ = (NimStringDesc*)0;
			T11_ = (*e).Sup.Sup.message; (*e).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_5));
			if (T11_) nimGCunrefNoCycle(T11_);
			asgnRef((void**) (&(*e).Sup.Sup.parent), NIM_NIL);
			raiseException((Exception*)e, "IOError");
		}
		LA9_: ;
	}
	LA4_: ;
	return result;
}

static N_INLINE(NIM_CHAR, X5BX5D__OfW9cXEAVaB9aahBBWfdc49cgbuild)(NimStringDesc* s, NI i) {
	NIM_CHAR result;
	result = (NIM_CHAR)0;
	result = s->data[(NI)((s ? s->Sup.len : 0) - i)];
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, noscreateDir)(NimStringDesc* dir) {
	NIM_BOOL omitNext;
	omitNext = NIM_FALSE;
	omitNext = nosisAbsolute(dir);
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)((dir ? dir->Sup.len : 0) - ((NI) 1));
		res = ((NI) 1);
		{
			while (1) {
				if (!(res <= colontmp_)) goto LA3;
				i = res;
				{
					if (!(((NU8)(dir->data[i])) == ((NU8)(92)) || ((NU8)(dir->data[i])) == ((NU8)(47)))) goto LA6_;
					{
						if (!omitNext) goto LA10_;
						omitNext = NIM_FALSE;
					}
					goto LA8_;
					LA10_: ;
					{
						NimStringDesc* T13_;
						NIM_BOOL T14_;
						T13_ = (NimStringDesc*)0;
						T13_ = copyStrLast(dir, ((NI) 0), (NI)(i - ((NI) 1)));
						T14_ = (NIM_BOOL)0;
						T14_ = existsOrCreateDir_45Xwkpg5BatjRqUBSXvMTQ(T13_);
						T14_;
					}
					LA8_: ;
				}
				LA6_: ;
				res += ((NI) 1);
			} LA3: ;
		}
	}
	{
		NIM_BOOL T17_;
		NIM_BOOL T18_;
		NIM_CHAR T21_;
		NIM_BOOL T24_;
		T17_ = (NIM_BOOL)0;
		T18_ = (NIM_BOOL)0;
		T18_ = (((NI) 0) < (dir ? dir->Sup.len : 0));
		if (!(T18_)) goto LA19_;
		T18_ = !(omitNext);
		LA19_: ;
		T17_ = T18_;
		if (!(T17_)) goto LA20_;
		T21_ = (NIM_CHAR)0;
		T21_ = X5BX5D__OfW9cXEAVaB9aahBBWfdc49cgbuild(dir, ((NI) 1));
		T17_ = !((((NU8)(T21_)) == ((NU8)(92)) || ((NU8)(T21_)) == ((NU8)(47))));
		LA20_: ;
		if (!T17_) goto LA22_;
		T24_ = (NIM_BOOL)0;
		T24_ = existsOrCreateDir_45Xwkpg5BatjRqUBSXvMTQ(dir);
		T24_;
	}
	LA22_: ;
}

N_LIB_PRIVATE N_NIMCALL(NI, findFirstFile_9cPKjuaUWDYlrzWunhDgNng)(NimStringDesc* a, tyObject_WIN32_FIND_DATA_aYwmSz9bIz0JHAL9ciwIrnhA* b) {
	NI result;
	NI16* T1_;
	result = (NI)0;
	T1_ = (NI16*)0;
	T1_ = newWideCString_keidLK9c3HkgArW69bcHZYGA(a);
	result = Dl_221237_(T1_, b);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI64, nosgetLastModificationTime)(NimStringDesc* file) {
	NI64 result;
	tyObject_WIN32_FIND_DATA_aYwmSz9bIz0JHAL9ciwIrnhA f;
	NI h;
	NI64 T6_;
	NI64 T7_;
	result = (NI64)0;
	memset((void*)(&f), 0, sizeof(f));
	h = findFirstFile_9cPKjuaUWDYlrzWunhDgNng(file, (&f));
	{
		NI32 T5_;
		if (!(h == ((NI) -1))) goto LA3_;
		T5_ = (NI32)0;
		T5_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T5_, ((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_3));
	}
	LA3_: ;
	T6_ = (NI64)0;
	T6_ = rdFileTime_8xfVp1z4bc5fRCRgoEFhIQ(f.ftLastWriteTime);
	T7_ = (NI64)0;
	T7_ = winTimeToUnixTime_0MF1tc32ZEJI7wo2ukv7DQ(T6_);
	result = fromUnix_C77WZNbbZYep1XVMN2QCfA(T7_);
	Dl_221401_(h);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosfileNewer)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NI64 T1_;
	NI64 T2_;
	NI64 T3_;
	result = (NIM_BOOL)0;
	T1_ = (NI64)0;
	T1_ = nosgetLastModificationTime(a);
	T2_ = (NI64)0;
	T2_ = nosgetLastModificationTime(b);
	T3_ = (NI64)0;
	T3_ = ntDiffTime(T1_, T2_);
	result = (IL64(0) < T3_);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, nossleep)(NI milsecs) {
	Dl_221629_(((NI32) (milsecs)));
}
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void) {
nimRegisterThreadLocalMarker(TM_yu6cxgKBBXbNsTkT9cyMd4g_2);
}

NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void) {
}

