/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_CONSOLE_SCREEN_BUFFER_INFO_r6d5R6U7A9aP1xHUbo2o04A tyObject_CONSOLE_SCREEN_BUFFER_INFO_r6d5R6U7A9aP1xHUbo2o04A;
typedef struct tyObject_COORD_38Oq1GgFPIYv2ksRi9c0fZA tyObject_COORD_38Oq1GgFPIYv2ksRi9c0fZA;
typedef struct tyObject_SMALL_RECT_GSDbaE1SdabWptSZYJG3XA tyObject_SMALL_RECT_GSDbaE1SdabWptSZYJG3XA;
typedef N_STDCALL_PTR(NI, tyProc_zP2zGemcuVRvOUE82f9a0Pw) (NI32 nStdHandle);
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_STDCALL_PTR(NI32, tyProc_oew1DfaGl5XhHmnBK0HYXQ) (NI hSourceProcessHandle, NI hSourceHandle, NI hTargetProcessHandle, NI* lpTargetHandle, NI32 dwDesiredAccess, NI32 bInheritHandle, NI32 dwOptions);
typedef N_STDCALL_PTR(NI, tyProc_uryidYWkntM7ddjZSyxvyQ) (void);
struct tyObject_COORD_38Oq1GgFPIYv2ksRi9c0fZA {
NI16 X;
NI16 Y;
};
struct tyObject_SMALL_RECT_GSDbaE1SdabWptSZYJG3XA {
NI16 Left;
NI16 Top;
NI16 Right;
NI16 Bottom;
};
struct tyObject_CONSOLE_SCREEN_BUFFER_INFO_r6d5R6U7A9aP1xHUbo2o04A {
tyObject_COORD_38Oq1GgFPIYv2ksRi9c0fZA dwSize;
tyObject_COORD_38Oq1GgFPIYv2ksRi9c0fZA dwCursorPosition;
NI16 wAttributes;
tyObject_SMALL_RECT_GSDbaE1SdabWptSZYJG3XA srWindow;
tyObject_COORD_38Oq1GgFPIYv2ksRi9c0fZA dwMaximumWindowSize;
};
typedef N_STDCALL_PTR(NI32, tyProc_vjGHiWUJwFzOgSxDffBb6Q) (NI hConsoleOutput, tyObject_CONSOLE_SCREEN_BUFFER_INFO_r6d5R6U7A9aP1xHUbo2o04A* lpConsoleScreenBufferInfo);
typedef NI tyArray_Bd4h7Ocx9bGTvrKzPIWNlHw[3];
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
N_LIB_PRIVATE N_NIMCALL(NI16, getAttributes_PnaHeFPQ8QlJWgnEjaRyCg)(NI h);
N_LIB_PRIVATE N_NIMCALL(NI, terminalWidthIoctl_9aOa3g2MGQEFvKhMvhVNbqw)(NI* handles, NI handlesLen_0);
NIM_BOOL trueColorIsSupported_kn9b0UIbK9cVbUGz9cl7kNkkw;
NIM_BOOL trueColorIsEnabled_Y9c1UaDywi8o8DHl8VRJG9cQ;
NIM_BOOL fgSetColor_az9a3BILKewIOic9a2Ah9a4tQ;
NI hStdout_Q6LBG8sK28zNgldP5VHBBA;
NI hStderr_6C9cOGHD37RMptVLFSz9ckEQ;
NI hStdoutTemp_Frgc1hZhHtHmhQpuiOhypw;
extern tyProc_zP2zGemcuVRvOUE82f9a0Pw Dl_220620_;
static void* TM_CN3raB9atujkEiPpxYAdlgQ_2;
tyProc_oew1DfaGl5XhHmnBK0HYXQ Dl_317439_;
tyProc_uryidYWkntM7ddjZSyxvyQ Dl_317449_;
NI hStderrTemp_lkKJFEg9bMgFJ9bv6dAcceSQ;
NI16 oldStdoutAttr_vkHOZle9bmebv77fjQpEGqw;
tyProc_vjGHiWUJwFzOgSxDffBb6Q Dl_317451_;
NI16 oldStderrAttr_ZXyw45dCi8lkCMLSUcaIBw;
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_4, "kernel32", 8);
STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_5, "kernel32", 8);

N_LIB_PRIVATE N_NIMCALL(NI16, getAttributes_PnaHeFPQ8QlJWgnEjaRyCg)(NI h) {
	NI16 result;
	tyObject_CONSOLE_SCREEN_BUFFER_INFO_r6d5R6U7A9aP1xHUbo2o04A c;
{	result = (NI16)0;
	memset((void*)(&c), 0, sizeof(c));
	{
		NI32 T3_;
		T3_ = (NI32)0;
		T3_ = Dl_317451_(h, (&c));
		if (!!((T3_ == ((NI32) 0)))) goto LA4_;
		result = c.wAttributes;
		goto BeforeRet_;
	}
	LA4_: ;
	result = ((NI16) 112);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, terminalWidthIoctl_9aOa3g2MGQEFvKhMvhVNbqw)(NI* handles, NI handlesLen_0) {
	NI result;
	tyObject_CONSOLE_SCREEN_BUFFER_INFO_r6d5R6U7A9aP1xHUbo2o04A csbi;
{	result = (NI)0;
	memset((void*)(&csbi), 0, sizeof(csbi));
	{
		NI h;
		NI i;
		h = (NI)0;
		i = ((NI) 0);
		{
			while (1) {
				if (!(i < handlesLen_0)) goto LA3;
				h = handles[i];
				{
					NI32 T6_;
					T6_ = (NI32)0;
					T6_ = Dl_317451_(h, (&csbi));
					if (!!((T6_ == ((NI32) 0)))) goto LA7_;
					result = ((NI) ((NI16)((NI16)(csbi.srWindow.Right - csbi.srWindow.Left) + ((NI16) 1))));
					goto BeforeRet_;
				}
				LA7_: ;
				i += ((NI) 1);
			} LA3: ;
		}
	}
	result = ((NI) 0);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, terminalWidth_PACsHLAgy9aMon9axrlFeqOQ)(void) {
	NI result;
	NI w;
	tyArray_Bd4h7Ocx9bGTvrKzPIWNlHw T1_;
{	result = (NI)0;
	w = ((NI) 0);
	T1_[0] = Dl_220620_(((NI32) -10));
	T1_[1] = Dl_220620_(((NI32) -11));
	T1_[2] = Dl_220620_(((NI32) -12));
	w = terminalWidthIoctl_9aOa3g2MGQEFvKhMvhVNbqw(T1_, 3);
	{
		if (!(((NI) 0) < w)) goto LA4_;
		result = w;
		goto BeforeRet_;
	}
	LA4_: ;
	result = ((NI) 80);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_terminalInit000)(void) {
	{
		hStdoutTemp_Frgc1hZhHtHmhQpuiOhypw = Dl_220620_(((NI32) -11));
		{
			NI T4_;
			NI T5_;
			NI32 T6_;
			T4_ = (NI)0;
			T4_ = Dl_317449_();
			T5_ = (NI)0;
			T5_ = Dl_317449_();
			T6_ = (NI32)0;
			T6_ = Dl_317439_(T4_, hStdoutTemp_Frgc1hZhHtHmhQpuiOhypw, T5_, (&hStdout_Q6LBG8sK28zNgldP5VHBBA), ((NI32) 0), ((NI32) 1), ((NI32) 2));
			if (!(T6_ == ((NI32) 0))) goto LA7_;
		}
		LA7_: ;
		hStderrTemp_lkKJFEg9bMgFJ9bv6dAcceSQ = Dl_220620_(((NI32) -12));
		{
			NI T11_;
			NI T12_;
			NI32 T13_;
			T11_ = (NI)0;
			T11_ = Dl_317449_();
			T12_ = (NI)0;
			T12_ = Dl_317449_();
			T13_ = (NI32)0;
			T13_ = Dl_317439_(T11_, hStderrTemp_lkKJFEg9bMgFJ9bv6dAcceSQ, T12_, (&hStderr_6C9cOGHD37RMptVLFSz9ckEQ), ((NI32) 0), ((NI32) 1), ((NI32) 2));
			if (!(T13_ == ((NI32) 0))) goto LA14_;
		}
		LA14_: ;
	}
	oldStdoutAttr_vkHOZle9bmebv77fjQpEGqw = getAttributes_PnaHeFPQ8QlJWgnEjaRyCg(hStdout_Q6LBG8sK28zNgldP5VHBBA);
	oldStderrAttr_ZXyw45dCi8lkCMLSUcaIBw = getAttributes_PnaHeFPQ8QlJWgnEjaRyCg(hStderr_6C9cOGHD37RMptVLFSz9ckEQ);
}

NIM_EXTERNC N_NOINLINE(void, stdlib_terminalDatInit000)(void) {
if (!((TM_CN3raB9atujkEiPpxYAdlgQ_2 = nimLoadLibrary((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_4))
)) nimLoadLibraryError((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_5);
	Dl_317439_ = (tyProc_oew1DfaGl5XhHmnBK0HYXQ) nimGetProcAddr(TM_CN3raB9atujkEiPpxYAdlgQ_2, "DuplicateHandle");
	Dl_317449_ = (tyProc_uryidYWkntM7ddjZSyxvyQ) nimGetProcAddr(TM_CN3raB9atujkEiPpxYAdlgQ_2, "GetCurrentProcess");
	Dl_317451_ = (tyProc_vjGHiWUJwFzOgSxDffBb6Q) nimGetProcAddr(TM_CN3raB9atujkEiPpxYAdlgQ_2, "GetConsoleScreenBufferInfo");
}

