/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
N_LIB_PRIVATE N_NIMCALL(NI64, toUnix_KOVzgXVRJxxlPUOsrk3eDQ)(NI64 t);

N_LIB_PRIVATE N_NIMCALL(NI64, toUnix_KOVzgXVRJxxlPUOsrk3eDQ)(NI64 t) {
	NI64 result;
	result = (NI64)0;
	result = t;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI64, ntDiffTime)(NI64 a, NI64 b) {
	NI64 result;
	NI64 T1_;
	NI64 T2_;
	result = (NI64)0;
	T1_ = (NI64)0;
	T1_ = toUnix_KOVzgXVRJxxlPUOsrk3eDQ(a);
	T2_ = (NI64)0;
	T2_ = toUnix_KOVzgXVRJxxlPUOsrk3eDQ(b);
	result = (NI64)(T1_ - T2_);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI64, fromUnix_C77WZNbbZYep1XVMN2QCfA)(NI64 unix) {
	NI64 result;
	result = (NI64)0;
	result = unix;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void) {
}

