/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <sys/types.h>
#define _GNU_SOURCE
#include <pthread.h>
#include <sys/types.h>
                          #include <pthread.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Table_SYjLU6M2sm9anvmSm6dqfCw tyObject_Table_SYjLU6M2sm9anvmSm6dqfCw;
typedef struct tySequence_X5VgSlRTnGqHdO9aaViz7mg tySequence_X5VgSlRTnGqHdO9aaViz7mg;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyTuple_uSRF9boiJ56eSspWN9aflKjw tyTuple_uSRF9boiJ56eSspWN9aflKjw;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_DependencycolonObjectType__iod5rMkNsUuEFhW1khjxow tyObject_DependencycolonObjectType__iod5rMkNsUuEFhW1khjxow;
typedef struct tyObject_Table_xVSF9cx9cwCUKA6pmggguBvw tyObject_Table_xVSF9cx9cwCUKA6pmggguBvw;
typedef struct tySequence_XEYKWyiTklhvm9cBmYMN9bcA tySequence_XEYKWyiTklhvm9cBmYMN9bcA;
typedef struct tyTuple_4oBY9crwUoDm8aNmyX79c0hg tyTuple_4oBY9crwUoDm8aNmyX79c0hg;
typedef struct tySequence_4eQHGndY6XBYpFOH09apV8Q tySequence_4eQHGndY6XBYpFOH09apV8Q;
typedef struct tyTuple_UV3llMMYFckfui8YMBuUZA tyTuple_UV3llMMYFckfui8YMBuUZA;
typedef struct tyObject_CountTable_WWp0VSBtrctjwzspLeGpeg tyObject_CountTable_WWp0VSBtrctjwzspLeGpeg;
typedef struct tySequence_jwzrUFjG9akTIJTBBFvvqxw tySequence_jwzrUFjG9akTIJTBBFvvqxw;
typedef struct tyTuple_XOVT24GHXwqiEj5GCsEGCA tyTuple_XOVT24GHXwqiEj5GCsEGCA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcThread_hgJQSlfXDOK3SwSHjeZBXg tyObject_GcThread_hgJQSlfXDOK3SwSHjeZBXg;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw;
typedef struct tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw;
typedef struct tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg;
typedef struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ;
typedef struct tySequence_SFipDZIkFtPcrLs0AGBBjQ tySequence_SFipDZIkFtPcrLs0AGBBjQ;
typedef struct tyTuple_8ZxhPt1NwfElsJs8zUSV9bg tyTuple_8ZxhPt1NwfElsJs8zUSV9bg;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tySequence_WF89a8QyKeDCh4DYWTmSiBg tySequence_WF89a8QyKeDCh4DYWTmSiBg;
typedef struct TSafePoint TSafePoint;
typedef struct GcFrameHeader GcFrameHeader;
struct tyObject_Table_SYjLU6M2sm9anvmSm6dqfCw {
tySequence_X5VgSlRTnGqHdO9aaViz7mg* data;
NI counter;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyTuple_uSRF9boiJ56eSspWN9aflKjw {
NI Field0;
NimStringDesc* Field1;
tyObject_DependencycolonObjectType__iod5rMkNsUuEFhW1khjxow* Field2;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Table_xVSF9cx9cwCUKA6pmggguBvw {
tySequence_XEYKWyiTklhvm9cBmYMN9bcA* data;
NI counter;
};
struct tyTuple_UV3llMMYFckfui8YMBuUZA {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
struct tyTuple_4oBY9crwUoDm8aNmyX79c0hg {
NI Field0;
NimStringDesc* Field1;
tySequence_4eQHGndY6XBYpFOH09apV8Q* Field2;
};
struct tyObject_CountTable_WWp0VSBtrctjwzspLeGpeg {
tySequence_jwzrUFjG9akTIJTBBFvvqxw* data;
NI counter;
};
struct tyTuple_XOVT24GHXwqiEj5GCsEGCA {
NimStringDesc* Field0;
NI Field1;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
typedef NF tyArray_iV2wVpdhi9coq9cstlcqapXg[2001];
struct tyObject_GcThread_hgJQSlfXDOK3SwSHjeZBXg {
tyArray_iV2wVpdhi9coq9cstlcqapXg tls;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw {
tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* head;
tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* tail;
pthread_mutex_t lock;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
tyObject_SharedList_9cWkTIPQvNw7gFHMOEzMCLw toDispose;
NI gcThreadId;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA {
  Exception Sup;
};
struct tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg {
  tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA Sup;
};
struct tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ {
tySequence_SFipDZIkFtPcrLs0AGBBjQ* data;
NI counter;
};
struct tyTuple_8ZxhPt1NwfElsJs8zUSV9bg {
NI Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
};
typedef NU8 tySet_tyEnum_FileTypes_2iO9c5w8zhYzUa1vVmCbznA;
struct tyObject_DependencycolonObjectType__iod5rMkNsUuEFhW1khjxow {
tySet_tyEnum_FileTypes_2iO9c5w8zhYzUa1vVmCbznA filetypes;
NimStringDesc* pathSource;
NimStringDesc* pathHeader;
NimStringDesc* dirSource;
NimStringDesc* dirHeader;
NIM_BOOL started;
NIM_BOOL finished;
NIM_BOOL compilable;
NIM_BOOL dirty;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* dependencies;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
typedef void* tyArray_Rrw59cMvNu8cDA9cQDh4v2oA[100];
struct tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw {
tyObject_SharedListNodecolonObjectType__82xHhBDm9bpijSPOyEGz0Hw* next;
NI dataLen;
tyArray_Rrw59cMvNu8cDA9cQDh4v2oA d;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc_hgOQFBQi19biNdOUUkFOOxA) (Exception* e);
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc_IIomJ6ptE6vfJ5zRbATgkQ;
struct tySequence_X5VgSlRTnGqHdO9aaViz7mg {
  TGenericSeq Sup;
  tyTuple_uSRF9boiJ56eSspWN9aflKjw data[SEQ_DECL_SIZE];
};
struct tySequence_4eQHGndY6XBYpFOH09apV8Q {
  TGenericSeq Sup;
  tyTuple_UV3llMMYFckfui8YMBuUZA data[SEQ_DECL_SIZE];
};
struct tySequence_XEYKWyiTklhvm9cBmYMN9bcA {
  TGenericSeq Sup;
  tyTuple_4oBY9crwUoDm8aNmyX79c0hg data[SEQ_DECL_SIZE];
};
struct tySequence_jwzrUFjG9akTIJTBBFvvqxw {
  TGenericSeq Sup;
  tyTuple_XOVT24GHXwqiEj5GCsEGCA data[SEQ_DECL_SIZE];
};
struct tySequence_SFipDZIkFtPcrLs0AGBBjQ {
  TGenericSeq Sup;
  tyTuple_8ZxhPt1NwfElsJs8zUSV9bg data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_WF89a8QyKeDCh4DYWTmSiBg {
  TGenericSeq Sup;
  tyProc_IIomJ6ptE6vfJ5zRbATgkQ data[SEQ_DECL_SIZE];
};
typedef struct {tyProc_hgOQFBQi19biNdOUUkFOOxA localRaiseHook_EIvMhANBvB9cp2Ezvt29cADg;
tySequence_WF89a8QyKeDCh4DYWTmSiBg* threadDestructionHandlers_8OmU3x0fNdA0DLtOmU3kWw;
NI threadId_wzrdPYhtL9czkCWS4o9an9cRw;
TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
Exception* currException_9bVPeDJlYTi9bQApZpfH8wjg;
GcFrameHeader* gcFramePtr_ot48iojqko9aFxGhyjjjVaA;
tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
NIM_BOOL envComputed_OC1kQm9aRvX8VnmaXglp57Q;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* environment_rnCB7Cc69bd2mlM49cn9czO2Q;
NI gFG_g7w4T3anr20OMlWloNx2tQ;
NI gBG_dgmeknpHWrtwqMJGQAp9atA;
} NimThreadVars;
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_X5VgSlRTnGqHdO9aaViz7mg)(void* p, NI op);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
static N_NIMCALL(void, Marker_tySequence_XEYKWyiTklhvm9cBmYMN9bcA)(void* p, NI op);
static N_NIMCALL(void, Marker_tySequence_jwzrUFjG9akTIJTBBFvvqxw)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(NI, rawGet_ExyNSxYFFaAiKxJjTjvq2w)(tyObject_CountTable_WWp0VSBtrctjwzspLeGpeg t, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(NI, hash_uBstFm5SYVQeOL3j9c9bc58A)(NimStringDesc* x);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash);
static N_INLINE(NIM_BOOL, mustRehash_CT8KHtrz1uoHrT4RgfOSmQtables)(NI length, NI counter);
N_LIB_PRIVATE N_NIMCALL(void, enlarge_jFpBafF2fWVni1oyF0vlQQ)(tyObject_CountTable_WWp0VSBtrctjwzspLeGpeg* t);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert_4Pv0wuM2j9aB1ybb1n9bQSkQ)(tyObject_CountTable_WWp0VSBtrctjwzspLeGpeg t, tySequence_jwzrUFjG9akTIJTBBFvvqxw** data, NimStringDesc* key, NI val);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void*, GetThreadLocalVars)(void);
static N_INLINE(void*, threadVarGetValue_F5t3jb8jndWAZxsO5Ba9bHwsystem)(pthread_key_t s);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
static N_NIMCALL(void, Marker_tySequence_SFipDZIkFtPcrLs0AGBBjQ)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_PO7qh9ayynagIdSmiclthWw)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(void, initTable_Pb6nsyDUqkcuOfIqNGZ04Q)(NI initialSize, tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ* Result);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__CM5QBhJw8HvPuuaSW9c6LyQ)(tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ* t, NimStringDesc* key, NimStringDesc* val);
static N_INLINE(NI, rawGet_9b2gsSftUX2T20Nv0GQyaugtables)(tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ t, NimStringDesc* key, NI* hc);
static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaewtables)(NI hcode);
N_LIB_PRIVATE N_NIMCALL(void, enlarge_9bBNTfkcWUAIzJYEZbqre3w)(tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ* t);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert_i52hhunrCCXlXL7airLPUA)(tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ* t, tySequence_SFipDZIkFtPcrLs0AGBBjQ** data, NimStringDesc* key, NimStringDesc* val, NI hc, NI h);
static N_INLINE(NI, rawGetKnownHC_t4rnRU9ceXEIukTl9b0Ap10Qtables)(tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ t, NimStringDesc* key, NI hc);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey_QpAX9allG2TL7zBzkNhhqPQ_2)(tyObject_Table_SYjLU6M2sm9anvmSm6dqfCw t, NimStringDesc* key);
static N_INLINE(NI, rawGet_muTCkXIw8TrxEW9cuztHf9aAtables)(tyObject_Table_SYjLU6M2sm9anvmSm6dqfCw t, NimStringDesc* key, NI* hc);
N_LIB_PRIVATE N_NIMCALL(void, enlarge_WXSfV2tkVd2ERvZgYpX1LQ)(tyObject_Table_SYjLU6M2sm9anvmSm6dqfCw* t);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert_Ad9coEBHZtpD8Bu3xmR1i7Q)(tyObject_Table_SYjLU6M2sm9anvmSm6dqfCw* t, tySequence_X5VgSlRTnGqHdO9aaViz7mg** data, NimStringDesc* key, tyObject_DependencycolonObjectType__iod5rMkNsUuEFhW1khjxow* val, NI hc, NI h);
static N_INLINE(NI, rawGetKnownHC_Y9bZFhucuVJ9bFt9bEO4734Ngtables)(tyObject_Table_SYjLU6M2sm9anvmSm6dqfCw t, NimStringDesc* key, NI hc);
TNimType NTI_SYjLU6M2sm9anvmSm6dqfCw_;
TNimType NTI_uSRF9boiJ56eSspWN9aflKjw_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI_7stfaUNLSE44EHEuGpsv5Q_;
TNimType NTI_X5VgSlRTnGqHdO9aaViz7mg_;
TNimType NTI_xVSF9cx9cwCUKA6pmggguBvw_;
TNimType NTI_4oBY9crwUoDm8aNmyX79c0hg_;
extern TNimType NTI_4eQHGndY6XBYpFOH09apV8Q_;
TNimType NTI_XEYKWyiTklhvm9cBmYMN9bcA_;
TNimType NTI_WWp0VSBtrctjwzspLeGpeg_;
TNimType NTI_XOVT24GHXwqiEj5GCsEGCA_;
TNimType NTI_jwzrUFjG9akTIJTBBFvvqxw_;
extern pthread_key_t globalsSlot_ciXDZu9c27pHpCRMoz4RIgw;
extern TNimType NTI_axqhRnwd09cVJkRcojfw6mA_;
extern TNimType NTI_ifYAhUumNzWR9c9cN9amyJLtg_;
TNimType NTI_MCOwvEd9cS88yVcSkkw9bO9aQ_;
TNimType NTI_8ZxhPt1NwfElsJs8zUSV9bg_;
TNimType NTI_SFipDZIkFtPcrLs0AGBBjQ_;
TNimType NTI_PO7qh9ayynagIdSmiclthWw_;
STRING_LITERAL(TM_4SoG2KRQy3oMm9aUzSLtGrA_8, "key not found: ", 15);
static N_NIMCALL(void, Marker_tySequence_X5VgSlRTnGqHdO9aaViz7mg)(void* p, NI op) {
	tySequence_X5VgSlRTnGqHdO9aaViz7mg* a;
	NI T1_;
	a = (tySequence_X5VgSlRTnGqHdO9aaViz7mg*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].Field1, op);
	nimGCvisit((void*)a->data[T1_].Field2, op);
	}
}

N_LIB_PRIVATE N_NIMCALL(void, initTable_voRQaw6UIHqRjsz7sup4bg)(NI initialSize, tyObject_Table_SYjLU6M2sm9anvmSm6dqfCw* Result) {
	genericReset((void*)Result, (&NTI_SYjLU6M2sm9anvmSm6dqfCw_));
	(*Result).counter = ((NI) 0);
	unsureAsgnRef((void**) (&(*Result).data), (tySequence_X5VgSlRTnGqHdO9aaViz7mg*) newSeq((&NTI_X5VgSlRTnGqHdO9aaViz7mg_), ((NI) (initialSize))));
}
static N_NIMCALL(void, Marker_tySequence_XEYKWyiTklhvm9cBmYMN9bcA)(void* p, NI op) {
	tySequence_XEYKWyiTklhvm9cBmYMN9bcA* a;
	NI T1_;
	a = (tySequence_XEYKWyiTklhvm9cBmYMN9bcA*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].Field1, op);
	nimGCvisit((void*)a->data[T1_].Field2, op);
	}
}

N_LIB_PRIVATE N_NIMCALL(void, initTable_RuKkt9biZ9ctYnGYw3kjEVzA)(NI initialSize, tyObject_Table_xVSF9cx9cwCUKA6pmggguBvw* Result) {
	genericReset((void*)Result, (&NTI_xVSF9cx9cwCUKA6pmggguBvw_));
	(*Result).counter = ((NI) 0);
	unsureAsgnRef((void**) (&(*Result).data), (tySequence_XEYKWyiTklhvm9cBmYMN9bcA*) newSeq((&NTI_XEYKWyiTklhvm9cBmYMN9bcA_), ((NI) (initialSize))));
}
static N_NIMCALL(void, Marker_tySequence_jwzrUFjG9akTIJTBBFvvqxw)(void* p, NI op) {
	tySequence_jwzrUFjG9akTIJTBBFvvqxw* a;
	NI T1_;
	a = (tySequence_jwzrUFjG9akTIJTBBFvvqxw*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].Field0, op);
	}
}

N_LIB_PRIVATE N_NIMCALL(void, initCountTable_n9cD2kEnW9cUab3V9bqtBxaTw)(NI initialSize, tyObject_CountTable_WWp0VSBtrctjwzspLeGpeg* Result) {
	genericReset((void*)Result, (&NTI_WWp0VSBtrctjwzspLeGpeg_));
	(*Result).counter = ((NI) 0);
	unsureAsgnRef((void**) (&(*Result).data), (tySequence_jwzrUFjG9akTIJTBBFvvqxw*) newSeq((&NTI_jwzrUFjG9akTIJTBBFvvqxw_), ((NI) (initialSize))));
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash) {
	NI result;
	result = (NI)0;
	result = (NI)((NI)(h + ((NI) 1)) & maxHash);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, rawGet_ExyNSxYFFaAiKxJjTjvq2w)(tyObject_CountTable_WWp0VSBtrctjwzspLeGpeg t, NimStringDesc* key) {
	NI result;
	NI h;
	NI T1_;
	NI T2_;
{	result = (NI)0;
	T1_ = (NI)0;
	T1_ = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	T2_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)(T1_ & T2_);
	{
		while (1) {
			NI T9_;
			if (!!((t.data->data[h].Field1 == ((NI) 0)))) goto LA4;
			{
				if (!eqStrings(t.data->data[h].Field0, key)) goto LA7_;
				result = h;
				goto BeforeRet_;
			}
			LA7_: ;
			T9_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T9_);
		} LA4: ;
	}
	result = (NI)(((NI) -1) - h);
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NIM_BOOL, mustRehash_CT8KHtrz1uoHrT4RgfOSmQtables)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	result = (NIM_BOOL)0;
	T1_ = (NIM_BOOL)0;
	T1_ = ((NI)(length * ((NI) 2)) < (NI)(counter * ((NI) 3)));
	if (T1_) goto LA2_;
	T1_ = ((NI)(length - counter) < ((NI) 4));
	LA2_: ;
	result = T1_;
	return result;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	return result;
}

static N_INLINE(void*, threadVarGetValue_F5t3jb8jndWAZxsO5Ba9bHwsystem)(pthread_key_t s) {
	void* result;
	result = (void*)0;
	result = pthread_getspecific(s);
	return result;
}

static N_INLINE(void*, GetThreadLocalVars)(void) {
	void* result;
	void* T1_;
	result = (void*)0;
	T1_ = (void*)0;
	T1_ = threadVarGetValue_F5t3jb8jndWAZxsO5Ba9bHwsystem(globalsSlot_ciXDZu9c27pHpCRMoz4RIgw);
	result = ((void*) ((*((tyObject_GcThread_hgJQSlfXDOK3SwSHjeZBXg*) (T1_))).tls));
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	NimThreadVars* NimTV_;
	NimTV_ = (NimThreadVars*) GetThreadLocalVars();
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&NimTV_->gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, rawInsert_4Pv0wuM2j9aB1ybb1n9bQSkQ)(tyObject_CountTable_WWp0VSBtrctjwzspLeGpeg t, tySequence_jwzrUFjG9akTIJTBBFvvqxw** data, NimStringDesc* key, NI val) {
	NI h;
	NI T1_;
	NI T2_;
	NimStringDesc* T6_;
	T1_ = (NI)0;
	T1_ = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	T2_ = ((*data) ? ((*data)->Sup.len-1) : -1);
	h = (NI)(T1_ & T2_);
	{
		while (1) {
			NI T5_;
			if (!!(((*data)->data[h].Field1 == ((NI) 0)))) goto LA4;
			T5_ = ((*data) ? ((*data)->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T5_);
		} LA4: ;
	}
	T6_ = (NimStringDesc*)0;
	T6_ = (*data)->data[h].Field0; (*data)->data[h].Field0 = copyStringRC1(key);
	if (T6_) nimGCunrefNoCycle(T6_);
	(*data)->data[h].Field1 = val;
}

N_LIB_PRIVATE N_NIMCALL(void, enlarge_jFpBafF2fWVni1oyF0vlQQ)(tyObject_CountTable_WWp0VSBtrctjwzspLeGpeg* t) {
	tySequence_jwzrUFjG9akTIJTBBFvvqxw* n;
	NI T1_;
	tySequence_jwzrUFjG9akTIJTBBFvvqxw* T10_;
	n = (tySequence_jwzrUFjG9akTIJTBBFvvqxw*)0;
	T1_ = ((*t).data ? (*t).data->Sup.len : 0);
	n = (tySequence_jwzrUFjG9akTIJTBBFvvqxw*) newSeq((&NTI_jwzrUFjG9akTIJTBBFvvqxw_), ((NI) ((NI)(T1_ * ((NI) 2)))));
	{
		NI i;
		NI colontmp_;
		NI T3_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		T3_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
		colontmp_ = T3_;
		res = ((NI) 0);
		{
			while (1) {
				if (!(res <= colontmp_)) goto LA5;
				i = res;
				{
					if (!!(((*t).data->data[i].Field1 == ((NI) 0)))) goto LA8_;
					rawInsert_4Pv0wuM2j9aB1ybb1n9bQSkQ((*t), (&n), (*t).data->data[i].Field0, (*t).data->data[i].Field1);
				}
				LA8_: ;
				res += ((NI) 1);
			} LA5: ;
		}
	}
	T10_ = (tySequence_jwzrUFjG9akTIJTBBFvvqxw*)0;
	T10_ = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = T10_;
}

N_LIB_PRIVATE N_NIMCALL(void, inc_hCwWEfjYY2mbkXPFg2lZFQ)(tyObject_CountTable_WWp0VSBtrctjwzspLeGpeg* t, NimStringDesc* key, NI val) {
	NI index;
	index = rawGet_ExyNSxYFFaAiKxJjTjvq2w((*t), key);
	{
		if (!(((NI) 0) <= index)) goto LA3_;
		(*t).data->data[index].Field1 += val;
		{
			if (!((*t).data->data[index].Field1 == ((NI) 0))) goto LA7_;
			(*t).counter -= ((NI) 1);
		}
		LA7_: ;
	}
	goto LA1_;
	LA3_: ;
	{
		{
			NI T12_;
			NIM_BOOL T13_;
			T12_ = ((*t).data ? (*t).data->Sup.len : 0);
			T13_ = (NIM_BOOL)0;
			T13_ = mustRehash_CT8KHtrz1uoHrT4RgfOSmQtables(T12_, (*t).counter);
			if (!T13_) goto LA14_;
			enlarge_jFpBafF2fWVni1oyF0vlQQ(t);
		}
		LA14_: ;
		rawInsert_4Pv0wuM2j9aB1ybb1n9bQSkQ((*t), (&(*t).data), key, val);
		(*t).counter += ((NI) 1);
	}
	LA1_: ;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		if (!!((src == NIM_NIL))) goto LA3_;
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	(*dest) = src;
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	(*dest) = src;
}

N_LIB_PRIVATE N_NIMCALL(NI*, X5BX5D__wKaBr49ajmFWIn1YkGn2RoA)(tyObject_CountTable_WWp0VSBtrctjwzspLeGpeg* t, NimStringDesc* key) {
	NI* result;
	NI index;
	result = (NI*)0;
	index = rawGet_ExyNSxYFFaAiKxJjTjvq2w((*t), key);
	{
		if (!(((NI) 0) <= index)) goto LA3_;
		result = (&(*t).data->data[index].Field1);
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg* e;
		NimStringDesc* T6_;
		e = (tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg*)0;
		e = (tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg*) newObj((&NTI_axqhRnwd09cVJkRcojfw6mA_), sizeof(tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg));
		(*e).Sup.Sup.Sup.m_type = (&NTI_ifYAhUumNzWR9c9cN9amyJLtg_);
		T6_ = (NimStringDesc*)0;
		T6_ = rawNewString(key->Sup.len + 15);
appendString(T6_, ((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_8));
appendString(T6_, key);
		asgnRefNoCycle((void**) (&(*e).Sup.Sup.message), T6_);
		asgnRef((void**) (&(*e).Sup.Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "KeyError");
	}
	LA1_: ;
	return result;
}
static N_NIMCALL(void, Marker_tySequence_SFipDZIkFtPcrLs0AGBBjQ)(void* p, NI op) {
	tySequence_SFipDZIkFtPcrLs0AGBBjQ* a;
	NI T1_;
	a = (tySequence_SFipDZIkFtPcrLs0AGBBjQ*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].Field1, op);
	nimGCvisit((void*)a->data[T1_].Field2, op);
	}
}
static N_NIMCALL(void, Marker_tyRef_PO7qh9ayynagIdSmiclthWw)(void* p, NI op) {
	tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ* a;
	a = (tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ*)p;
	nimGCvisit((void*)(*a).data, op);
}

N_LIB_PRIVATE N_NIMCALL(void, initTable_Pb6nsyDUqkcuOfIqNGZ04Q)(NI initialSize, tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ* Result) {
	genericReset((void*)Result, (&NTI_MCOwvEd9cS88yVcSkkw9bO9aQ_));
	(*Result).counter = ((NI) 0);
	unsureAsgnRef((void**) (&(*Result).data), (tySequence_SFipDZIkFtPcrLs0AGBBjQ*) newSeq((&NTI_SFipDZIkFtPcrLs0AGBBjQ_), ((NI) (initialSize))));
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ*, newTable_jIjJCqCQw4Fh4gFygl450w)(NI initialSize) {
	tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ* result;
	result = (tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ*)0;
	result = (tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ*) newObj((&NTI_PO7qh9ayynagIdSmiclthWw_), sizeof(tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ));
	initTable_Pb6nsyDUqkcuOfIqNGZ04Q(initialSize, (&(*result)));
	return result;
}

static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaewtables)(NI hcode) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = !((hcode == ((NI) 0)));
	return result;
}

static N_INLINE(NI, rawGet_9b2gsSftUX2T20Nv0GQyaugtables)(tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI T5_;
{	result = (NI)0;
	(*hc) = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	T5_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)((*hc) & T5_);
	{
		while (1) {
			NIM_BOOL T8_;
			NI T15_;
			T8_ = (NIM_BOOL)0;
			T8_ = isFilled_IxXD1UAPoEehVDW9cv9cRaewtables(t.data->data[h].Field0);
			if (!T8_) goto LA7;
			{
				NIM_BOOL T11_;
				T11_ = (NIM_BOOL)0;
				T11_ = (t.data->data[h].Field0 == (*hc));
				if (!(T11_)) goto LA12_;
				T11_ = eqStrings(t.data->data[h].Field1, key);
				LA12_: ;
				if (!T11_) goto LA13_;
				result = h;
				goto BeforeRet_;
			}
			LA13_: ;
			T15_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T15_);
		} LA7: ;
	}
	result = (NI)(((NI) -1) - h);
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, rawInsert_i52hhunrCCXlXL7airLPUA)(tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ* t, tySequence_SFipDZIkFtPcrLs0AGBBjQ** data, NimStringDesc* key, NimStringDesc* val, NI hc, NI h) {
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	T1_ = (NimStringDesc*)0;
	T1_ = (*data)->data[h].Field1; (*data)->data[h].Field1 = copyStringRC1(key);
	if (T1_) nimGCunrefNoCycle(T1_);
	T2_ = (NimStringDesc*)0;
	T2_ = (*data)->data[h].Field2; (*data)->data[h].Field2 = copyStringRC1(val);
	if (T2_) nimGCunrefNoCycle(T2_);
	(*data)->data[h].Field0 = hc;
}

N_LIB_PRIVATE N_NIMCALL(void, enlarge_9bBNTfkcWUAIzJYEZbqre3w)(tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ* t) {
	tySequence_SFipDZIkFtPcrLs0AGBBjQ* n;
	NI T1_;
	tySequence_SFipDZIkFtPcrLs0AGBBjQ* T2_;
	n = (tySequence_SFipDZIkFtPcrLs0AGBBjQ*)0;
	T1_ = ((*t).data ? (*t).data->Sup.len : 0);
	n = (tySequence_SFipDZIkFtPcrLs0AGBBjQ*) newSeq((&NTI_SFipDZIkFtPcrLs0AGBBjQ_), ((NI) ((NI)(T1_ * ((NI) 2)))));
	T2_ = (tySequence_SFipDZIkFtPcrLs0AGBBjQ*)0;
	T2_ = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = T2_;
	{
		NI i;
		NI colontmp_;
		NI T4_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		T4_ = (n ? (n->Sup.len-1) : -1);
		colontmp_ = T4_;
		res = ((NI) 0);
		{
			while (1) {
				NI eh;
				if (!(res <= colontmp_)) goto LA6;
				i = res;
				eh = n->data[i].Field0;
				{
					NIM_BOOL T9_;
					NI j;
					NI T12_;
					T9_ = (NIM_BOOL)0;
					T9_ = isFilled_IxXD1UAPoEehVDW9cv9cRaewtables(eh);
					if (!T9_) goto LA10_;
					T12_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
					j = (NI)(eh & T12_);
					{
						while (1) {
							NIM_BOOL T15_;
							NI T16_;
							T15_ = (NIM_BOOL)0;
							T15_ = isFilled_IxXD1UAPoEehVDW9cv9cRaewtables((*t).data->data[j].Field0);
							if (!T15_) goto LA14;
							T16_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
							j = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(j, T16_);
						} LA14: ;
					}
					rawInsert_i52hhunrCCXlXL7airLPUA(t, (&(*t).data), n->data[i].Field1, n->data[i].Field2, eh, j);
				}
				LA10_: ;
				res += ((NI) 1);
			} LA6: ;
		}
	}
}

static N_INLINE(NI, rawGetKnownHC_t4rnRU9ceXEIukTl9b0Ap10Qtables)(tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ t, NimStringDesc* key, NI hc) {
	NI result;
	NI h;
	NI T1_;
{	result = (NI)0;
	T1_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)(hc & T1_);
	{
		while (1) {
			NIM_BOOL T4_;
			NI T11_;
			T4_ = (NIM_BOOL)0;
			T4_ = isFilled_IxXD1UAPoEehVDW9cv9cRaewtables(t.data->data[h].Field0);
			if (!T4_) goto LA3;
			{
				NIM_BOOL T7_;
				T7_ = (NIM_BOOL)0;
				T7_ = (t.data->data[h].Field0 == hc);
				if (!(T7_)) goto LA8_;
				T7_ = eqStrings(t.data->data[h].Field1, key);
				LA8_: ;
				if (!T7_) goto LA9_;
				result = h;
				goto BeforeRet_;
			}
			LA9_: ;
			T11_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T11_);
		} LA3: ;
	}
	result = (NI)(((NI) -1) - h);
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__CM5QBhJw8HvPuuaSW9c6LyQ)(tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ* t, NimStringDesc* key, NimStringDesc* val) {
	NI hc;
	NI index;
	hc = (NI)0;
	index = rawGet_9b2gsSftUX2T20Nv0GQyaugtables((*t), key, (&hc));
	{
		NimStringDesc* T5_;
		if (!(((NI) 0) <= index)) goto LA3_;
		T5_ = (NimStringDesc*)0;
		T5_ = (*t).data->data[index].Field2; (*t).data->data[index].Field2 = copyStringRC1(val);
		if (T5_) nimGCunrefNoCycle(T5_);
	}
	goto LA1_;
	LA3_: ;
	{
		{
			NI T9_;
			NIM_BOOL T10_;
			T9_ = ((*t).data ? (*t).data->Sup.len : 0);
			T10_ = (NIM_BOOL)0;
			T10_ = mustRehash_CT8KHtrz1uoHrT4RgfOSmQtables(T9_, (*t).counter);
			if (!T10_) goto LA11_;
			enlarge_9bBNTfkcWUAIzJYEZbqre3w(t);
			index = rawGetKnownHC_t4rnRU9ceXEIukTl9b0Ap10Qtables((*t), key, hc);
		}
		LA11_: ;
		index = (NI)(((NI) -1) - index);
		rawInsert_i52hhunrCCXlXL7airLPUA(t, (&(*t).data), key, val, hc, index);
		(*t).counter += ((NI) 1);
	}
	LA1_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__KZ6cH9cdWNLGQvShJR8Hr9cg)(tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ* t, NimStringDesc* key, NimStringDesc* val) {
	X5BX5Deq__CM5QBhJw8HvPuuaSW9c6LyQ(t, key, val);
}

static N_INLINE(NI, rawGet_muTCkXIw8TrxEW9cuztHf9aAtables)(tyObject_Table_SYjLU6M2sm9anvmSm6dqfCw t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI T5_;
{	result = (NI)0;
	(*hc) = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	T5_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)((*hc) & T5_);
	{
		while (1) {
			NIM_BOOL T8_;
			NI T15_;
			T8_ = (NIM_BOOL)0;
			T8_ = isFilled_IxXD1UAPoEehVDW9cv9cRaewtables(t.data->data[h].Field0);
			if (!T8_) goto LA7;
			{
				NIM_BOOL T11_;
				T11_ = (NIM_BOOL)0;
				T11_ = (t.data->data[h].Field0 == (*hc));
				if (!(T11_)) goto LA12_;
				T11_ = eqStrings(t.data->data[h].Field1, key);
				LA12_: ;
				if (!T11_) goto LA13_;
				result = h;
				goto BeforeRet_;
			}
			LA13_: ;
			T15_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T15_);
		} LA7: ;
	}
	result = (NI)(((NI) -1) - h);
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey_QpAX9allG2TL7zBzkNhhqPQ_2)(tyObject_Table_SYjLU6M2sm9anvmSm6dqfCw t, NimStringDesc* key) {
	NIM_BOOL result;
	NI hc;
	NI T1_;
	result = (NIM_BOOL)0;
	hc = (NI)0;
	T1_ = (NI)0;
	T1_ = rawGet_muTCkXIw8TrxEW9cuztHf9aAtables(t, key, (&hc));
	result = (((NI) 0) <= T1_);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains_QpAX9allG2TL7zBzkNhhqPQ)(tyObject_Table_SYjLU6M2sm9anvmSm6dqfCw t, NimStringDesc* key) {
	NIM_BOOL result;
{	result = (NIM_BOOL)0;
	result = hasKey_QpAX9allG2TL7zBzkNhhqPQ_2(t, key);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, rawInsert_Ad9coEBHZtpD8Bu3xmR1i7Q)(tyObject_Table_SYjLU6M2sm9anvmSm6dqfCw* t, tySequence_X5VgSlRTnGqHdO9aaViz7mg** data, NimStringDesc* key, tyObject_DependencycolonObjectType__iod5rMkNsUuEFhW1khjxow* val, NI hc, NI h) {
	NimStringDesc* T1_;
	T1_ = (NimStringDesc*)0;
	T1_ = (*data)->data[h].Field1; (*data)->data[h].Field1 = copyStringRC1(key);
	if (T1_) nimGCunrefNoCycle(T1_);
	asgnRefNoCycle((void**) (&(*data)->data[h].Field2), val);
	(*data)->data[h].Field0 = hc;
}

N_LIB_PRIVATE N_NIMCALL(void, enlarge_WXSfV2tkVd2ERvZgYpX1LQ)(tyObject_Table_SYjLU6M2sm9anvmSm6dqfCw* t) {
	tySequence_X5VgSlRTnGqHdO9aaViz7mg* n;
	NI T1_;
	tySequence_X5VgSlRTnGqHdO9aaViz7mg* T2_;
	n = (tySequence_X5VgSlRTnGqHdO9aaViz7mg*)0;
	T1_ = ((*t).data ? (*t).data->Sup.len : 0);
	n = (tySequence_X5VgSlRTnGqHdO9aaViz7mg*) newSeq((&NTI_X5VgSlRTnGqHdO9aaViz7mg_), ((NI) ((NI)(T1_ * ((NI) 2)))));
	T2_ = (tySequence_X5VgSlRTnGqHdO9aaViz7mg*)0;
	T2_ = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = T2_;
	{
		NI i;
		NI colontmp_;
		NI T4_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		T4_ = (n ? (n->Sup.len-1) : -1);
		colontmp_ = T4_;
		res = ((NI) 0);
		{
			while (1) {
				NI eh;
				if (!(res <= colontmp_)) goto LA6;
				i = res;
				eh = n->data[i].Field0;
				{
					NIM_BOOL T9_;
					NI j;
					NI T12_;
					T9_ = (NIM_BOOL)0;
					T9_ = isFilled_IxXD1UAPoEehVDW9cv9cRaewtables(eh);
					if (!T9_) goto LA10_;
					T12_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
					j = (NI)(eh & T12_);
					{
						while (1) {
							NIM_BOOL T15_;
							NI T16_;
							T15_ = (NIM_BOOL)0;
							T15_ = isFilled_IxXD1UAPoEehVDW9cv9cRaewtables((*t).data->data[j].Field0);
							if (!T15_) goto LA14;
							T16_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
							j = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(j, T16_);
						} LA14: ;
					}
					rawInsert_Ad9coEBHZtpD8Bu3xmR1i7Q(t, (&(*t).data), n->data[i].Field1, n->data[i].Field2, eh, j);
				}
				LA10_: ;
				res += ((NI) 1);
			} LA6: ;
		}
	}
}

static N_INLINE(NI, rawGetKnownHC_Y9bZFhucuVJ9bFt9bEO4734Ngtables)(tyObject_Table_SYjLU6M2sm9anvmSm6dqfCw t, NimStringDesc* key, NI hc) {
	NI result;
	NI h;
	NI T1_;
{	result = (NI)0;
	T1_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)(hc & T1_);
	{
		while (1) {
			NIM_BOOL T4_;
			NI T11_;
			T4_ = (NIM_BOOL)0;
			T4_ = isFilled_IxXD1UAPoEehVDW9cv9cRaewtables(t.data->data[h].Field0);
			if (!T4_) goto LA3;
			{
				NIM_BOOL T7_;
				T7_ = (NIM_BOOL)0;
				T7_ = (t.data->data[h].Field0 == hc);
				if (!(T7_)) goto LA8_;
				T7_ = eqStrings(t.data->data[h].Field1, key);
				LA8_: ;
				if (!T7_) goto LA9_;
				result = h;
				goto BeforeRet_;
			}
			LA9_: ;
			T11_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T11_);
		} LA3: ;
	}
	result = (NI)(((NI) -1) - h);
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__AllIlOn9bY6Bt2W4MDQTAeQ)(tyObject_Table_SYjLU6M2sm9anvmSm6dqfCw* t, NimStringDesc* key, tyObject_DependencycolonObjectType__iod5rMkNsUuEFhW1khjxow* val) {
	NI hc;
	NI index;
	hc = (NI)0;
	index = rawGet_muTCkXIw8TrxEW9cuztHf9aAtables((*t), key, (&hc));
	{
		if (!(((NI) 0) <= index)) goto LA3_;
		asgnRefNoCycle((void**) (&(*t).data->data[index].Field2), val);
	}
	goto LA1_;
	LA3_: ;
	{
		{
			NI T8_;
			NIM_BOOL T9_;
			T8_ = ((*t).data ? (*t).data->Sup.len : 0);
			T9_ = (NIM_BOOL)0;
			T9_ = mustRehash_CT8KHtrz1uoHrT4RgfOSmQtables(T8_, (*t).counter);
			if (!T9_) goto LA10_;
			enlarge_WXSfV2tkVd2ERvZgYpX1LQ(t);
			index = rawGetKnownHC_Y9bZFhucuVJ9bFt9bEO4734Ngtables((*t), key, hc);
		}
		LA10_: ;
		index = (NI)(((NI) -1) - index);
		rawInsert_Ad9coEBHZtpD8Bu3xmR1i7Q(t, (&(*t).data), key, val, hc, index);
		(*t).counter += ((NI) 1);
	}
	LA1_: ;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_DependencycolonObjectType__iod5rMkNsUuEFhW1khjxow**, X5BX5D__n8a53Wid8gI46oYLICnUEw)(tyObject_Table_SYjLU6M2sm9anvmSm6dqfCw* t, NimStringDesc* key) {
	tyObject_DependencycolonObjectType__iod5rMkNsUuEFhW1khjxow** result;
	NI hc;
	NI index;
	result = (tyObject_DependencycolonObjectType__iod5rMkNsUuEFhW1khjxow**)0;
	hc = (NI)0;
	index = rawGet_muTCkXIw8TrxEW9cuztHf9aAtables((*t), key, (&hc));
	{
		if (!(((NI) 0) <= index)) goto LA3_;
		result = &(*t).data->data[index].Field2;
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg* e;
		NimStringDesc* T6_;
		e = (tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg*)0;
		e = (tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg*) newObj((&NTI_axqhRnwd09cVJkRcojfw6mA_), sizeof(tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg));
		(*e).Sup.Sup.Sup.m_type = (&NTI_ifYAhUumNzWR9c9cN9amyJLtg_);
		T6_ = (NimStringDesc*)0;
		T6_ = rawNewString(key->Sup.len + 15);
appendString(T6_, ((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_8));
appendString(T6_, key);
		asgnRefNoCycle((void**) (&(*e).Sup.Sup.message), T6_);
		asgnRef((void**) (&(*e).Sup.Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "KeyError");
	}
	LA1_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKeyOrPut_hvcWqigcdSM9c4IgnQQvdfg)(tyObject_Table_SYjLU6M2sm9anvmSm6dqfCw* t, NimStringDesc* key, tyObject_DependencycolonObjectType__iod5rMkNsUuEFhW1khjxow* val) {
	NIM_BOOL result;
	NI hc;
	NI index;
	result = (NIM_BOOL)0;
	hc = (NI)0;
	index = rawGet_muTCkXIw8TrxEW9cuztHf9aAtables((*t), key, (&hc));
	{
		if (!(index < ((NI) 0))) goto LA3_;
		result = NIM_FALSE;
		{
			NI T7_;
			NIM_BOOL T8_;
			T7_ = ((*t).data ? (*t).data->Sup.len : 0);
			T8_ = (NIM_BOOL)0;
			T8_ = mustRehash_CT8KHtrz1uoHrT4RgfOSmQtables(T7_, (*t).counter);
			if (!T8_) goto LA9_;
			enlarge_WXSfV2tkVd2ERvZgYpX1LQ(t);
			index = rawGetKnownHC_Y9bZFhucuVJ9bFt9bEO4734Ngtables((*t), key, hc);
		}
		LA9_: ;
		index = (NI)(((NI) -1) - index);
		rawInsert_Ad9coEBHZtpD8Bu3xmR1i7Q(t, (&(*t).data), key, val, hc, index);
		(*t).counter += ((NI) 1);
	}
	goto LA1_;
	LA3_: ;
	{
		result = NIM_TRUE;
	}
	LA1_: ;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void) {
static TNimNode* TM_4SoG2KRQy3oMm9aUzSLtGrA_2[2];
static TNimNode* TM_4SoG2KRQy3oMm9aUzSLtGrA_3[3];
static TNimNode* TM_4SoG2KRQy3oMm9aUzSLtGrA_4[2];
static TNimNode* TM_4SoG2KRQy3oMm9aUzSLtGrA_5[3];
static TNimNode* TM_4SoG2KRQy3oMm9aUzSLtGrA_6[2];
static TNimNode* TM_4SoG2KRQy3oMm9aUzSLtGrA_7[2];
static TNimNode* TM_4SoG2KRQy3oMm9aUzSLtGrA_9[2];
static TNimNode* TM_4SoG2KRQy3oMm9aUzSLtGrA_10[3];
static TNimNode TM_4SoG2KRQy3oMm9aUzSLtGrA_0[27];
NTI_SYjLU6M2sm9anvmSm6dqfCw_.size = sizeof(tyObject_Table_SYjLU6M2sm9anvmSm6dqfCw);
NTI_SYjLU6M2sm9anvmSm6dqfCw_.kind = 18;
NTI_SYjLU6M2sm9anvmSm6dqfCw_.base = 0;
NTI_SYjLU6M2sm9anvmSm6dqfCw_.flags = 2;
TM_4SoG2KRQy3oMm9aUzSLtGrA_2[0] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1];
NTI_uSRF9boiJ56eSspWN9aflKjw_.size = sizeof(tyTuple_uSRF9boiJ56eSspWN9aflKjw);
NTI_uSRF9boiJ56eSspWN9aflKjw_.kind = 18;
NTI_uSRF9boiJ56eSspWN9aflKjw_.base = 0;
NTI_uSRF9boiJ56eSspWN9aflKjw_.flags = 2;
TM_4SoG2KRQy3oMm9aUzSLtGrA_3[0] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3].offset = offsetof(tyTuple_uSRF9boiJ56eSspWN9aflKjw, Field0);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3].name = "Field0";
TM_4SoG2KRQy3oMm9aUzSLtGrA_3[1] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4].offset = offsetof(tyTuple_uSRF9boiJ56eSspWN9aflKjw, Field1);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4].name = "Field1";
TM_4SoG2KRQy3oMm9aUzSLtGrA_3[2] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5].offset = offsetof(tyTuple_uSRF9boiJ56eSspWN9aflKjw, Field2);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5].typ = (&NTI_7stfaUNLSE44EHEuGpsv5Q_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5].name = "Field2";
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[2].len = 3; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[2].kind = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[2].sons = &TM_4SoG2KRQy3oMm9aUzSLtGrA_3[0];
NTI_uSRF9boiJ56eSspWN9aflKjw_.node = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[2];
NTI_X5VgSlRTnGqHdO9aaViz7mg_.size = sizeof(tySequence_X5VgSlRTnGqHdO9aaViz7mg*);
NTI_X5VgSlRTnGqHdO9aaViz7mg_.kind = 24;
NTI_X5VgSlRTnGqHdO9aaViz7mg_.base = (&NTI_uSRF9boiJ56eSspWN9aflKjw_);
NTI_X5VgSlRTnGqHdO9aaViz7mg_.flags = 2;
NTI_X5VgSlRTnGqHdO9aaViz7mg_.marker = Marker_tySequence_X5VgSlRTnGqHdO9aaViz7mg;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1].offset = offsetof(tyObject_Table_SYjLU6M2sm9anvmSm6dqfCw, data);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1].typ = (&NTI_X5VgSlRTnGqHdO9aaViz7mg_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1].name = "data";
TM_4SoG2KRQy3oMm9aUzSLtGrA_2[1] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6].offset = offsetof(tyObject_Table_SYjLU6M2sm9anvmSm6dqfCw, counter);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6].name = "counter";
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[0].len = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[0].kind = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[0].sons = &TM_4SoG2KRQy3oMm9aUzSLtGrA_2[0];
NTI_SYjLU6M2sm9anvmSm6dqfCw_.node = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[0];
NTI_xVSF9cx9cwCUKA6pmggguBvw_.size = sizeof(tyObject_Table_xVSF9cx9cwCUKA6pmggguBvw);
NTI_xVSF9cx9cwCUKA6pmggguBvw_.kind = 18;
NTI_xVSF9cx9cwCUKA6pmggguBvw_.base = 0;
NTI_xVSF9cx9cwCUKA6pmggguBvw_.flags = 2;
TM_4SoG2KRQy3oMm9aUzSLtGrA_4[0] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[8];
NTI_4oBY9crwUoDm8aNmyX79c0hg_.size = sizeof(tyTuple_4oBY9crwUoDm8aNmyX79c0hg);
NTI_4oBY9crwUoDm8aNmyX79c0hg_.kind = 18;
NTI_4oBY9crwUoDm8aNmyX79c0hg_.base = 0;
NTI_4oBY9crwUoDm8aNmyX79c0hg_.flags = 2;
TM_4SoG2KRQy3oMm9aUzSLtGrA_5[0] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[10];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[10].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[10].offset = offsetof(tyTuple_4oBY9crwUoDm8aNmyX79c0hg, Field0);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[10].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[10].name = "Field0";
TM_4SoG2KRQy3oMm9aUzSLtGrA_5[1] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[11];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[11].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[11].offset = offsetof(tyTuple_4oBY9crwUoDm8aNmyX79c0hg, Field1);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[11].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[11].name = "Field1";
TM_4SoG2KRQy3oMm9aUzSLtGrA_5[2] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[12];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[12].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[12].offset = offsetof(tyTuple_4oBY9crwUoDm8aNmyX79c0hg, Field2);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[12].typ = (&NTI_4eQHGndY6XBYpFOH09apV8Q_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[12].name = "Field2";
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[9].len = 3; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[9].kind = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[9].sons = &TM_4SoG2KRQy3oMm9aUzSLtGrA_5[0];
NTI_4oBY9crwUoDm8aNmyX79c0hg_.node = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[9];
NTI_XEYKWyiTklhvm9cBmYMN9bcA_.size = sizeof(tySequence_XEYKWyiTklhvm9cBmYMN9bcA*);
NTI_XEYKWyiTklhvm9cBmYMN9bcA_.kind = 24;
NTI_XEYKWyiTklhvm9cBmYMN9bcA_.base = (&NTI_4oBY9crwUoDm8aNmyX79c0hg_);
NTI_XEYKWyiTklhvm9cBmYMN9bcA_.flags = 2;
NTI_XEYKWyiTklhvm9cBmYMN9bcA_.marker = Marker_tySequence_XEYKWyiTklhvm9cBmYMN9bcA;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[8].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[8].offset = offsetof(tyObject_Table_xVSF9cx9cwCUKA6pmggguBvw, data);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[8].typ = (&NTI_XEYKWyiTklhvm9cBmYMN9bcA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[8].name = "data";
TM_4SoG2KRQy3oMm9aUzSLtGrA_4[1] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[13];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[13].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[13].offset = offsetof(tyObject_Table_xVSF9cx9cwCUKA6pmggguBvw, counter);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[13].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[13].name = "counter";
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[7].len = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[7].kind = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[7].sons = &TM_4SoG2KRQy3oMm9aUzSLtGrA_4[0];
NTI_xVSF9cx9cwCUKA6pmggguBvw_.node = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[7];
NTI_WWp0VSBtrctjwzspLeGpeg_.size = sizeof(tyObject_CountTable_WWp0VSBtrctjwzspLeGpeg);
NTI_WWp0VSBtrctjwzspLeGpeg_.kind = 18;
NTI_WWp0VSBtrctjwzspLeGpeg_.base = 0;
NTI_WWp0VSBtrctjwzspLeGpeg_.flags = 2;
TM_4SoG2KRQy3oMm9aUzSLtGrA_6[0] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[15];
NTI_XOVT24GHXwqiEj5GCsEGCA_.size = sizeof(tyTuple_XOVT24GHXwqiEj5GCsEGCA);
NTI_XOVT24GHXwqiEj5GCsEGCA_.kind = 18;
NTI_XOVT24GHXwqiEj5GCsEGCA_.base = 0;
NTI_XOVT24GHXwqiEj5GCsEGCA_.flags = 2;
TM_4SoG2KRQy3oMm9aUzSLtGrA_7[0] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[17];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[17].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[17].offset = offsetof(tyTuple_XOVT24GHXwqiEj5GCsEGCA, Field0);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[17].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[17].name = "Field0";
TM_4SoG2KRQy3oMm9aUzSLtGrA_7[1] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[18];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[18].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[18].offset = offsetof(tyTuple_XOVT24GHXwqiEj5GCsEGCA, Field1);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[18].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[18].name = "Field1";
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[16].len = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[16].kind = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[16].sons = &TM_4SoG2KRQy3oMm9aUzSLtGrA_7[0];
NTI_XOVT24GHXwqiEj5GCsEGCA_.node = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[16];
NTI_jwzrUFjG9akTIJTBBFvvqxw_.size = sizeof(tySequence_jwzrUFjG9akTIJTBBFvvqxw*);
NTI_jwzrUFjG9akTIJTBBFvvqxw_.kind = 24;
NTI_jwzrUFjG9akTIJTBBFvvqxw_.base = (&NTI_XOVT24GHXwqiEj5GCsEGCA_);
NTI_jwzrUFjG9akTIJTBBFvvqxw_.flags = 2;
NTI_jwzrUFjG9akTIJTBBFvvqxw_.marker = Marker_tySequence_jwzrUFjG9akTIJTBBFvvqxw;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[15].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[15].offset = offsetof(tyObject_CountTable_WWp0VSBtrctjwzspLeGpeg, data);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[15].typ = (&NTI_jwzrUFjG9akTIJTBBFvvqxw_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[15].name = "data";
TM_4SoG2KRQy3oMm9aUzSLtGrA_6[1] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[19];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[19].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[19].offset = offsetof(tyObject_CountTable_WWp0VSBtrctjwzspLeGpeg, counter);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[19].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[19].name = "counter";
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[14].len = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[14].kind = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[14].sons = &TM_4SoG2KRQy3oMm9aUzSLtGrA_6[0];
NTI_WWp0VSBtrctjwzspLeGpeg_.node = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[14];
NTI_MCOwvEd9cS88yVcSkkw9bO9aQ_.size = sizeof(tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ);
NTI_MCOwvEd9cS88yVcSkkw9bO9aQ_.kind = 18;
NTI_MCOwvEd9cS88yVcSkkw9bO9aQ_.base = 0;
NTI_MCOwvEd9cS88yVcSkkw9bO9aQ_.flags = 2;
TM_4SoG2KRQy3oMm9aUzSLtGrA_9[0] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[21];
NTI_8ZxhPt1NwfElsJs8zUSV9bg_.size = sizeof(tyTuple_8ZxhPt1NwfElsJs8zUSV9bg);
NTI_8ZxhPt1NwfElsJs8zUSV9bg_.kind = 18;
NTI_8ZxhPt1NwfElsJs8zUSV9bg_.base = 0;
NTI_8ZxhPt1NwfElsJs8zUSV9bg_.flags = 2;
TM_4SoG2KRQy3oMm9aUzSLtGrA_10[0] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[23];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[23].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[23].offset = offsetof(tyTuple_8ZxhPt1NwfElsJs8zUSV9bg, Field0);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[23].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[23].name = "Field0";
TM_4SoG2KRQy3oMm9aUzSLtGrA_10[1] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[24];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[24].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[24].offset = offsetof(tyTuple_8ZxhPt1NwfElsJs8zUSV9bg, Field1);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[24].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[24].name = "Field1";
TM_4SoG2KRQy3oMm9aUzSLtGrA_10[2] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[25];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[25].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[25].offset = offsetof(tyTuple_8ZxhPt1NwfElsJs8zUSV9bg, Field2);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[25].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[25].name = "Field2";
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[22].len = 3; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[22].kind = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[22].sons = &TM_4SoG2KRQy3oMm9aUzSLtGrA_10[0];
NTI_8ZxhPt1NwfElsJs8zUSV9bg_.node = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[22];
NTI_SFipDZIkFtPcrLs0AGBBjQ_.size = sizeof(tySequence_SFipDZIkFtPcrLs0AGBBjQ*);
NTI_SFipDZIkFtPcrLs0AGBBjQ_.kind = 24;
NTI_SFipDZIkFtPcrLs0AGBBjQ_.base = (&NTI_8ZxhPt1NwfElsJs8zUSV9bg_);
NTI_SFipDZIkFtPcrLs0AGBBjQ_.flags = 2;
NTI_SFipDZIkFtPcrLs0AGBBjQ_.marker = Marker_tySequence_SFipDZIkFtPcrLs0AGBBjQ;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[21].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[21].offset = offsetof(tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ, data);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[21].typ = (&NTI_SFipDZIkFtPcrLs0AGBBjQ_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[21].name = "data";
TM_4SoG2KRQy3oMm9aUzSLtGrA_9[1] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[26];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[26].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[26].offset = offsetof(tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ, counter);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[26].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[26].name = "counter";
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[20].len = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[20].kind = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[20].sons = &TM_4SoG2KRQy3oMm9aUzSLtGrA_9[0];
NTI_MCOwvEd9cS88yVcSkkw9bO9aQ_.node = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[20];
NTI_PO7qh9ayynagIdSmiclthWw_.size = sizeof(tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ*);
NTI_PO7qh9ayynagIdSmiclthWw_.kind = 22;
NTI_PO7qh9ayynagIdSmiclthWw_.base = (&NTI_MCOwvEd9cS88yVcSkkw9bO9aQ_);
NTI_PO7qh9ayynagIdSmiclthWw_.flags = 2;
NTI_PO7qh9ayynagIdSmiclthWw_.marker = Marker_tyRef_PO7qh9ayynagIdSmiclthWw;
}

